const fs = require('fs');
const path = require('path');

function countWords(str) {
  return str.trim().split(/\s+/).filter(Boolean).length;
}

const { expansionsPart1 } = require('./expand_part1.cjs');

const lessons = [];

function addLesson(id, title, category, paragraphs) {
  let allParas = [...paragraphs];
  let content = allParas.filter(Boolean).map(p => p.trim()).join('\n\n');
  let words = countWords(content);
  if (words < 700 && expansionsPart1[id]) {
    allParas = allParas.concat(expansionsPart1[id]);
    content = allParas.filter(Boolean).map(p => p.trim()).join('\n\n');
    words = countWords(content);
  }
  if (words < 700) {
    throw new Error(`Lesson ${id} (${title}) has only ${words} words, needs at least 700!`);
  }
  lessons.push({ id, title, category, content, words });
}

// 1. Rajasthan Geography & Physical Divisions
addLesson(1, "Exercise : 1/100 - Rajasthan Geography & Physical Divisions", "Rajasthan Geography", [
  `Rajasthan is the largest state in the Republic of India in terms of total geographical area, covering approximately three hundred forty-two thousand two hundred thirty-nine square kilometres, which represents about 10.41 percent of the total landmass of India. Situated in the north-western region of the subcontinent, it shares international boundaries with Pakistan across five border districts in the west and northwest, while bordering the Indian states of Punjab, Haryana, Uttar Pradesh, Madhya Pradesh, and Gujarat. The tropic of cancer passes through the southernmost tip of the state, traversing the districts of Banswara and Dungarpur. The physical geography of Rajasthan presents a fascinating mosaic of extreme climatic variations, diverse geological formations, distinct soil profiles, and unique biological adaptations. Understanding these physical characteristics is essential for administrative personnel to plan regional developmental projects, water distribution networks, and disaster management strategies efficiently.`,
  `The state is broadly classified into four major physiographic divisions: the Western Sandy Plains or the Great Indian Thar Desert, the Aravalli Mountain Range, the Eastern Plains, and the South-Eastern Hadoti Plateau. The Western Sandy Plains encompass more than sixty percent of the state total land area and are home to nearly forty percent of its population. This arid tract is further subdivided into the Marusthali, characterized by shifting sand dunes known as Dhrians, and the semi-arid Rajasthan Bagar, which includes inland drainage basins such as the Shekhawati tract and the fertile Luni River basin. Despite severe climatic constraints, sparse rainfall, and extreme temperature fluctuations, the Thar Desert is considered one of the most densely populated desert ecosystems in the world, sustained by resilient pastoral communities, hardy desert livestock, and innovative traditional rainwater collection systems.`,
  `The Aravalli Mountain Range is one of the oldest fold mountain systems in the world, dating back to the Precambrian geological era. Running diagonally across Rajasthan from southwest near Mount Abu to northeast up to the Khetri belt and extending to the Raisina Hill in New Delhi, the Aravalli range spans approximately six hundred ninety-two kilometres, with five hundred fifty kilometres lying entirely within Rajasthan. Guru Shikhar, situated near Mount Abu in the Sirohi district, stands as the highest peak of the range with an elevation of one thousand seven hundred twenty-two metres above mean sea level. The Aravallis act as a crucial watershed and climatic divide, preventing the eastward expansion of the Thar Desert into the fertile agricultural plains of eastern Rajasthan and Madhya Pradesh, while also serving as the source for several major seasonal river systems including the Banas, Luni, Sabarmati, and Sukri.`,
  `The Eastern Plains of Rajasthan lie to the east of the central Aravalli hills, encompassing the fertile river basins of the Banas, Banganga, and the Middle Mahi river, also known as the Chappan Plain in the Banswara and Pratapgarh region. Formed primarily by extensive alluvial deposits brought down by perennial and seasonal river streams, these plains possess highly productive soils such as loamy sand and clayey loam, supporting intensive multi-crop agriculture including wheat, mustard, barley, and pulses. In contrast, the South-Eastern Hadoti Plateau, covering districts like Kota, Bundi, Baran, and Jhalawar, represents an extension of the Deccan Lava Trap, characterized by rich black cotton soil, undulating basaltic terrain, and significant limestone deposits. This region receives the highest average annual precipitation in the state and is extensively drained by the perennial Chambal river and its tributaries, making it a major powerhouse for agro-industries and thermal power generation.`,
  `For administrative officers and ministerial staff preparing for Rajasthan state examinations, mastering the detailed nuances of physical geography is vital. Land revenue administration, district boundary demarcations, crop insurance assessments, drought relief allocations, and watershed management all depend heavily on accurate geographical understanding. Clerks must accurately record local land classification terminology such as Chahi (irrigated land), Barani (unirrigated rainfed land), and Magra (rocky hill slopes) in village land revenue registers. Familiarity with topographical maps, district profiles, agro-climatic zones, and ground water vulnerability indexes ensures that clerical support in government secretariats and district collectorates contributes directly to sound policymaking, balanced regional development, and effective public grievance redressal across the state.`,
  `Furthermore, the ongoing administrative restructuring and formation of new districts in Rajasthan highlights the necessity of geographic literacy in governance. Realigned boundaries require revenue personnel to re-catalogue land parcels, adjust catchment areas, recalibrate sub-divisional jurisdictions, and update GIS mapping layers on the state Bhunaksha digital land portal. Field functionaries must evaluate regional micro-climates, soil fertility indices, and mineral belts when recommending industrial park allocations or municipal extensions. Mastery over geographical facts is therefore not merely an academic exercise for competitive examinations, but a practical requirement for ensuring equitable public administration and sustainable resource utilization across every corner of the state.`
]);

// 2. Historic Forts and World Heritage Sites
addLesson(2, "Exercise : 2/100 - Historic Forts and World Heritage Sites", "Art & Culture", [
  `The architectural brilliance, chivalric heritage, and heroic saga of Rajasthan are immortalized in its majestic hill forts, formidable citadel ramparts, and opulent royal palaces. In 2013, the World Heritage Committee of UNESCO officially designated six magnificent hill forts of Rajasthan as UNESCO World Heritage Sites, celebrating their outstanding universal value, strategic defensive engineering, and rich cultural syncretism. These six celebrated monuments include Chittorgarh Fort, Kumbhalgarh Fort in Rajsamand, Sawai Madhopur Ranthambore Fort, Jaisalmer Fort, Gagron Fort in Jhalawar, and Amber Fort in Jaipur. Spread across distinct geographical terrains ranging from dense forests and rugged Aravalli ridges to expansive desert sands and river confluences, these forts illustrate the pinnacle of Rajput defensive military architecture evolved over centuries between the eighth and nineteenth centuries.`,
  `Chittorgarh Fort, perched atop a steep five-hundred-foot-high rocky plateau, stands as an eternal monument to Rajput valour, patriotism, and the supreme sacrifice of Jauhar. Spanning over seven hundred acres, it is recognized as the largest fort complex in India and was the legendary capital of the Sisodia dynasty of Mewar. Within its massive stone ramparts lie historic landmarks such as the nine-storey Vijay Stambha or Tower of Victory erected by Maharana Kumbha to commemorate his victory over the armies of Malwa and Gujarat, the Kirti Stambha dedicated to Jain Tirthankara Adinatha, and the historic palaces of Maharana Ratan Singh and Rani Padmini. The fort endured three epic sieges by Alauddin Khalji, Bahadur Shah of Gujarat, and Mughal Emperor Akbar, each followed by heroic battles and tragic collective sacrifices that continue to inspire Rajasthani folk ballads and national historical memory.`,
  `Kumbhalgarh Fort, situated amidst the rugged ridges of the western Aravalli range in Rajsamand district, is renowned worldwide for possessing the second-longest continuous fortification wall on Earth, stretching over thirty-six kilometres and wide enough for multiple horsemen to ride abreast. Built during the fifteenth century by Maharana Kumbha under the architectural guidance of master builder Mandan, Kumbhalgarh was designed to be virtually impregnable, serving as a secure royal refuge during times of foreign invasion. It is celebrated as the birthplace of Maharana Pratap and contains over three hundred sixty ancient Hindu and Jain temples, alongside the Badal Mahal palace crowning the highest cliff. Further east, the Gagron Fort in Jhalawar represents an exceptional example of a Jal Durg or water fort, surrounded on three sides by the swirling waters of the Ahu and Kali Sindh rivers without needing an artificial moat.`,
  `In the arid western desert, Jaisalmer Fort, affectionately called Sonar Qila or the Golden Fort, rises like a golden mirage from the Trikuta Hill amidst shifting sands. Built in 1156 AD by Rawal Jaisal using indigenous yellow Jurassic sandstone, it is one of the very few living forts in the world, with nearly a fourth of the old city population residing within its triple-layered defensive walls. The fort houses exquisite Jain temples adorned with intricate Torana gateways and delicate filigree stone carvings, alongside the Raj Mahal palace and the invaluable manuscripts preserved in the Jinbhadra Suri Gyan Bhandar. In Jaipur, Amber Fort displays a splendid synthesis of Rajput and Mughal artistic traditions, featuring the world-famous Sheesh Mahal inlaid with Belgian convex mirrors, grand courtyards, and the sacred Shila Devi temple. Preserving these invaluable monuments fosters global tourism, generates sustainable local employment, and protects the living traditions of Rajasthan.`,
  `From an administrative and conservation perspective, managing these world heritage properties involves coordinated efforts between the Archaeological Survey of India (ASI), the State Department of Archaeology and Museums, and local municipal corporations. Clerks and administrative officers handle budgeting for archaeological restorations, tourist facilitation facilities, encroachment monitoring, light and sound show operations, and international cultural exchange protocols. Rigorous documentation, record upkeep, and transparent management ensure that the architectural glory and cultural dignity of Rajasthan historic fortresses continue to inspire generations of domestic and international visitors.`,
  `Preserving the physical integrity of these historic monuments in the twenty-first century demands modern conservation protocols, including structural stone consolidation, eco-sensitive buffer zone enforcement, sustainable tourist carrying-capacity modeling, and community engagement. Ministerial officers in the Department of Tourism and Culture draft annual monument maintenance budgets, process archaeological clearance dossiers for infrastructure projects, and coordinate tourist safety measures with heritage police battalions. The enduring majesty of Rajasthan hill forts serves as a living testament to the engineering genius, spiritual devotion, and immortal heroism of its builders, continuing to captivate historians and travelers worldwide.`
]);

// 3. The Role of Lower Division Clerks in Administration
addLesson(3, "Exercise : 3/100 - The Role of Lower Division Clerks in Administration", "Office Procedures", [
  `The Lower Division Clerk, commonly designated as LDC or Junior Assistant in government departments and subordinate offices of Rajasthan, forms the fundamental administrative backbone of public service delivery. The functioning of government secretariats, directorates, collectorates, municipal bodies, and public utility offices relies heavily on the efficiency, accuracy, and diligence of ministerial staff. The primary duties of an LDC encompass receiving and registering incoming postal and electronic correspondence (Dak), diarizing files, maintaining department subject registers, preparing standard office notes, cross-referencing statutory rules and historical precedents, and ensuring prompt dispatch of executive orders to subordinate field offices and concerned citizens.`,
  `With the comprehensive modernization of public administration through digital governance platforms, such as the integrated e-Office suite and RajKaj portal, the traditional role of ministerial clerks has evolved from physical paper filing to high-speed digital record management. Clerks are now required to possess exceptional bilingual typing speed and precision in both English and Hindi, along with working proficiency in word processing, electronic spreadsheets, database querying, and secure digital signature validation. Typing speed evaluation tests conducted by the Rajasthan Staff Selection Board (RSSB) are designed with rigorous standards to ensure that recruited personnel can draft official memorandums, generate statistical reports, and process citizen grievance files without introducing errors or administrative delays.`,
  `A crucial dimension of a clerk daily responsibility is the strict adherence to the Secretariat Manual of Office Procedure (SMOP) and the Rajasthan Service Rules (RSR). Every incoming file must follow an established movement register, with noting drafted on the left-hand side of the docket and correspondence placed on the right-hand side. Clerks must carefully analyze the legal, administrative, and financial implications of every case before placing it before Section Officers, Assistant Secretaries, or District Collectors. A well-trained clerk understands the distinction between Routine Notes, Detailed Notes, and Summary Proposals, ensuring that concise, factual, and unambiguous summaries are placed before executive decision-makers for timely sanctions and policy clearances.`,
  `In addition to general file management, clerks working in establishment, accounts, and legal branches handle critical tasks such as employee pay fixation, maintenance of service books, leave entitlement calculations, pension proposal drafting, and assembling replies for Right to Information (RTI) petitions and legislative assembly questions. Accuracy in numerical calculations, dates, and statutory citations is paramount; an oversight in record-keeping can result in legal disputes, audit objections, or denial of legitimate welfare benefits to citizens. Therefore, ministerial civil servants must uphold the highest standards of professional integrity, confidentiality, and citizen-centric responsiveness, ensuring that public administration in Rajasthan operates with exemplary transparency, promptness, and administrative fairness.`,
  `Continuous professional skill enhancement and technological adaptability are vital for career progression from Junior Assistant to Senior Assistant, Assistant Section Officer, and Section Officer. As government departments transition towards artificial intelligence-driven document summarization, automated grievance categorization, and paperless workflows, clerks who maintain exceptional typing fluency, meticulous attention to detail, and a deep understanding of administrative jurisprudence will remain indispensable contributors to effective governance and citizen satisfaction in Rajasthan.`,
  `Furthermore, ministerial personnel act as the primary interface between the citizen and the state machinery during public hearing days, Jan Sunwai camps, and revenue lok adalats. Recording citizen petitions accurately, tagging them with appropriate departmental subject codes, issuing instant acknowledgement receipts, and following up on pending compliance reports requires strong empathetic communication skills alongside clerical competence. A punctual, dedicated, and computer-literate Lower Division Clerk accelerates the entire administrative apparatus, transforming bureaucratic paperwork into rapid, tangible public service outcomes for millions of citizens.`,
  `Ethical conduct and data security form additional pillars of ministerial responsibility. Clerical staff handle confidential government records, public procurement bids, and citizen personal data protected under statutory privacy norms. Adhering strictly to the Rajasthan Civil Services Conduct Rules, preventing unauthorized file disclosures, and maintaining clean, audit-compliant physical and digital file archives reinforces public trust in democratic institutions and administrative governance. Ministerial employees must continually refine their drafting competencies to reflect executive decisions with legal precision.`,
  `Finally, time management and prioritized file disposal schedules dictate clerical efficiency during peak administrative periods such as legislative assembly sessions and annual budget formulations. Tracking urgent assembly questions, compiling starred question background dossiers under strict deadlines, and coordinating with subordinate field directorates requires tireless dedication. Clerks who master these multifaceted administrative responsibilities serve as the true bedrock of effective democratic governance across Rajasthan.`
]);

// 4. Indira Gandhi Canal Project (IGNP)
addLesson(4, "Exercise : 4/100 - Indira Gandhi Canal Project (IGNP)", "Water Resources & Irrigation", [
  `Originating from the Harike Barrage in Punjab at the confluence of the Satluj and Beas rivers, the Indira Gandhi Canal Project (IGNP) is one of the most gigantic and ambitious irrigation canal networks in human history. Conceived by visionary engineer Kanwar Sain in 1948 to transform the arid wilderness of north-western Rajasthan into a productive green belt, the project was officially launched in 1958. It stretches across hundreds of kilometres through the states of Punjab, Haryana, and Rajasthan, terminating in the desert expanses of Jaisalmer and Barmer. The main canal, known as the Rajasthan Feeder and Rajasthan Main Canal, spans over six hundred forty-nine kilometres, accompanied by an extensive network of distribution channels, branches, and lift canals exceeding nine thousand kilometres in total length.`,
  `The command area of the Indira Gandhi Canal is administratively categorized into Stage One and Stage Two. Stage One covers the northern districts of Sri Ganganagar, Hanumangarh, and parts of Bikaner, utilizing flow irrigation across relatively flatter plains. Stage Two extends into the more challenging desert terrain of Bikaner, Jaisalmer, Jodhpur, Nagaur, and Barmer, where water must be mechanically lifted using lift canals such as the Kanwar Sain Lift Canal, Gandheli Sahawa Lift Canal, Gajner Lift Canal, Kolayat Lift Canal, Phalodi Lift Canal, and Pokhran Lift Canal. The introduction of perennial canal water has triggered an unprecedented socioeconomic transformation, facilitating drinking water supply for millions of desert residents, supporting livestock herds, and enabling the commercial cultivation of cash crops including cotton, wheat, mustard, guar, groundnut, and kinnow citrus orchards.`,
  `Despite its monumental developmental benefits, the Indira Gandhi Canal Project presents substantial environmental and ecological challenges that require continuous engineering oversight and administrative interventions. Uncontrolled flood irrigation across porous sandy soils underlain by impervious gypsum layers has led to severe waterlogging, soil salinization, and rising groundwater tables in low-lying depressions of Rawatsar and Hanumangarh. Furthermore, intensive silt deposition along unlined channels and weed infestation reduce canal flow velocity, requiring regular desiltation campaigns and modern canal lining works. The state command area development authority (CADA) actively promotes sprinkler irrigation systems, pressurized pipe distribution networks, and community water user associations (WUA) to maximize water use efficiency.`,
  `For administrative clerks and revenue officials in canal command districts, managing canal-related files demands familiarity with technical terminology such as Chak (irrigation unit), Warabandi (rotational water distribution timetable), Mogha (canal water outlet), and Murabba (standard land division square). Revenue records must reflect precise water shares, crop loss assessments during seasonal canal closures, and distribution of subsidized sprinkler equipment. As climate variability and inter-state river water sharing treaties evolve, the optimal operation of the Indira Gandhi Canal remains central to the agricultural prosperity, food security, and ecological balance of western Rajasthan.`,
  `The ongoing modernization of the canal network incorporates supervisory control and data acquisition (SCADA) systems, automated flow gates, and drone surveillance to detect breaches and illegal water siphoning. Sustainable desert agriculture under the IGNP represents a global benchmark for converting inhospitable arid landscapes into thriving agricultural hubs through engineering excellence, sound governance, and community resilience.`,
  `Additionally, canal command development has fostered the growth of agro-processing industrial corridors, mandis, and warehousing hubs across Ganganagar, Bikaner, and Hanumangarh. Transporting agricultural produce from desert farm gates to national consumer markets has boosted per capita district incomes. Ensuring equitable water distribution at the tail-ends of distributaries remains a high administrative priority, demanding daily monitoring by irrigation executive engineers, revenue tehsildars, and ministerial desk officers.`,
  `Afforestation belts planted along canal banks, known as shelterbelts, stabilize shifting sand dunes and prevent sand accumulation in water channels. These canal-side plantations of Dalbergia sissoo (Shisham), Acacia tortilis, and Tecomella undulata (Rohida) enhance local micro-climates, support biodiversity, and supply valuable timber, exemplifying an integrated approach to desert ecosystem management. Sustaining this hydrological marvel requires continuous investment in lining, desiltation, and community participatory water governance.`,
  `Moreover, the canal plays an indispensable strategic role along India western international frontier, supplying clean drinking water to remote Border Security Force (BSF) outposts and border villages. The economic and strategic security conferred by the IGNP has converted previously inhospitable desert stretches into vibrant, self-reliant agrarian communities contributing significantly to national food reserves.`,
  `Finally, administrative personnel must track inter-state water regulation protocols agreed upon within the Bhakra Beas Management Board (BBMB) framework. Accurately recording daily canal gauge readings at feeder intake points, monitoring discharge cubic feet per second (cusecs), and preparing seasonal water allocation memorandums ensures that Rajasthan receives its legitimate statutory share of river waters. Continuous vigilance by clerical and technical staff sustains the lifeblood of the Thar Desert.`
]);

// 5. Computer Fundamentals and Hardware Architecture
addLesson(5, "Exercise : 5/100 - Computer Fundamentals and Hardware Architecture", "Computer Fundamentals", [
  `A modern electronic digital computer is an advanced system designed to accept raw data as input, process it through a sequence of logical and arithmetical instructions, store intermediate and permanent records, and generate meaningful output for users. In modern public administration, computers have completely replaced traditional manual ledger systems, forming the core infrastructure for e-governance, digital treasury management, and citizen database maintenance. A comprehensive understanding of computer architecture, internal hardware components, peripheral devices, and system software is essential for clerical candidates seeking employment in government secretariats and public sector undertakings.`,
  `The Central Processing Unit, commonly known as the CPU, acts as the primary computational engine and brain of the computer system. It consists of three fundamental structural modules: the Arithmetic Logic Unit (ALU), which performs all mathematical calculations and relational logical comparisons; the Control Unit (CU), which orchestrates the fetch, decode, and execute cycle across all connected subsystems; and internal high-speed register arrays that provide temporary storage for active data operands. Modern CPUs utilize multi-core architectures, enabling parallel execution of multiple software threads, which drastically speeds up document processing, statistical indexing, and encrypted data transmission.`,
  `System memory is hierarchically structured to balance operational speed, data persistence, and cost. Primary storage consists of Random Access Memory (RAM), which is volatile and holds currently active programs and operating system routines, and Read Only Memory (ROM), which permanently stores firmware instructions such as the Basic Input Output System (BIOS) or Unified Extensible Firmware Interface (UEFI) required to bootstrap the machine. Cache memory, situated directly on or adjacent to the processor die, provides lightning-fast access to frequently referenced instructions. Secondary storage encompasses non-volatile storage mediums including Solid State Drives (SSD), Hard Disk Drives (HDD), and external optical or magnetic storage media, providing secure long-term repository for administrative databases.`,
  `Input devices allow clerical operators to feed alphanumeric text and commands into the computer. Standard input peripherals include mechanical and membrane keyboards, optical mice, document scanners, biometric fingerprint readers, and Optical Mark Recognition (OMR) scanners used in public examinations. Output peripherals translate processed digital signals into human-readable formats, comprising High Definition visual display monitors, laser printers for generating official gazette notifications, dot matrix printers for multi-copy receipts, and high-speed network plotters for engineering blueprints. Connecting these peripherals requires standard high-speed bus interfaces such as Universal Serial Bus (USB), HDMI, DisplayPort, and PCIe expansion slots.`,
  `Clerical officers must be equipped with practical hardware troubleshooting capabilities, including verifying device driver installations in the Device Manager, diagnosing memory bottlenecks using the Task Manager, configuring network printers, and ensuring proper power backup through Uninterruptible Power Supply (UPS) units. Maintaining hardware security, preventing unauthorized access through USB port blocking protocols, and executing periodic system backups protect sensitive governmental records from hardware failures and unauthorized tampering.`,
  `Furthermore, understanding system bus topologies—including the control bus, data bus, and address bus—provides insight into data throughput bottlenecks. Knowledge of motherboard chipsets, thermal dissipation mechanisms such as heat sinks and cooling fans, and surge suppression safeguards hardware longevity in government office environments. Clerks who can quickly identify whether a malfunction stems from a loose SATA cable, faulty RAM seating, or a corrupted display adapter save valuable working hours and sustain uninterrupted public service workflows.`,
  `Regular preventative hardware maintenance, such as dust cleaning of CPU ventilation grilles, testing uninterruptible power supply (UPS) batteries, and verifying disk health using SMART diagnostics, prevents sudden hardware breakdowns. As public administration increasingly relies on 24/7 digital public service portals, hardware reliability and prompt desktop troubleshooting are critical for maintaining administrative productivity. Mastery over foundational computer hardware architectures ensures seamless transition to advanced digital administrative workflows.`
]);

// 6. Unification and Integration of Rajasthan
addLesson(6, "Exercise : 6/100 - Unification and Integration of Rajasthan", "Rajasthan History", [
  `The political integration of Rajasthan into the democratic fabric of independent India stands as an extraordinary achievement of statesmanship, constitutional diplomacy, and visionary leadership. Prior to August 1947, the region was officially designated by British colonial authorities as Rajputana, an intricate political mosaic comprising nineteen sovereign princely states, three independent chiefships (Lawa, Neemrana, and Kushalgarh), and the centrally administered British enclave of Ajmer-Merwara. These princely territories varied vastly in geographic extent, financial stability, military capability, and administrative development. Integrating these autonomous rulers into a unified modern democratic state was orchestrated masterfully by India Iron Man, Sardar Vallabhbhai Patel, and the astute Secretary of the Ministry of States, V. P. Menon.`,
  `The grand unification of Rajasthan was accomplished through seven distinct historical stages between 1948 and 1956. The first stage commenced on March 18, 1948, with the establishment of the Matsya Union, bringing together the four eastern states of Alwar, Bharatpur, Dholpur, and Karauli, with Alwar serving as its administrative capital. Shortly thereafter, the second stage witnessed the creation of Rajasthan Union on March 25, 1948, integrating nine southeastern princely states including Banswara, Bundi, Dungarpur, Jhalawar, Kishangarh, Kota, Pratapgarh, Shahpura, and Tonk, alongside Kushalgarh chiefship, with Maharao Bhim Singh of Kota sworn in as Rajpramukh.`,
  `The third stage, known as the United State of Rajasthan, materialized on April 18, 1948, when the historic and prestigious state of Mewar (Udaipur) merged into the union. Pandit Jawaharlal Nehru inaugurated this expanded entity in Udaipur, appointing Maharana Bhupal Singh as Rajpramukh and Manikya Lal Verma as Prime Minister. The fourth stage represented the pivotal breakthrough on March 30, 1949, when the four largest desert kingdoms—Jaipur, Jodhpur, Bikaner, and Jaisalmer—joined the union, creating Greater Rajasthan (Brihat Rajasthan). Sardar Patel formally inaugurated this historic milestone in Jaipur, appointing Maharaja Sawai Man Singh II of Jaipur as Rajpramukh and Hiralal Shastri as the first Chief Minister. Ever since, March 30 is commemorated annually across the state as Rajasthan Day (Rajasthan Diwas).`,
  `The fifth stage occurred on May 15, 1949, when the Matsya Union was amalgamated into Greater Rajasthan following the recommendations of the Dr. Shankarrao Deo Committee, establishing the United State of Greater Rajasthan. The sixth stage occurred on January 26, 1950, coinciding with the enforcement of the Constitution of India, when Sirohi state (excluding Abu and Delwara tehsils) was integrated into Rajasthan. The seventh and final stage took effect on November 1, 1956, based on the landmark recommendations of the States Reorganisation Commission headed by Justice Fazal Ali. Under this conclusive reorganization, the centrally administered territory of Ajmer-Merwara, the Abu and Delwara regions of Sirohi, and the Sunel Tappa enclave of Madhya Pradesh were formally integrated into Rajasthan, while the Sironj sub-district was transferred to Madhya Pradesh.`,
  `This monumental political consolidation established the territorial boundaries of contemporary Rajasthan, comprising twenty-six administrative districts in 1956. Understanding the chronological sequence, covenant conditions, privy purse provisions, and constitutional transitions of these seven stages is essential for ministerial civil servants. Administrative clerks in the General Administration Department (GAD) and Revenue Department frequently process historical land grants (Jagir resumptions), princely covenant records, and inter-state boundary agreements that trace directly back to these integration treaties. The integration of Rajasthan reflects the triumph of democratic aspirations, turning feudal monarchies into a vibrant, unified state committed to social equity, constitutional democracy, and progressive governance.`,
  `Furthermore, the merger required establishing a unified civil service, harmonizing divergent princely revenue laws, standardizing court jurisdictions under the Rajasthan High Court at Jodhpur, and integrating regional police forces into the unified Rajasthan Police. Civil servants played a foundational role in re-cataloguing state treasury assets, establishing district collectorates, and extending democratic adult franchise into rural hamlets. The unification of Rajasthan remains one of the greatest administrative triumphs in modern Indian history.`
]);

// 7. Panchayati Raj System and Nagaur Milestone
addLesson(7, "Exercise : 7/100 - Panchayati Raj System and Nagaur Milestone", "Polity & Governance", [
  `Rajasthan holds a revered and pioneering position in the constitutional and democratic history of modern India as the historic birthplace of the institutionalized Panchayati Raj system. On October 2, 1959, commemorating the birth anniversary of Mahatma Gandhi, the first Prime Minister of independent India, Pandit Jawaharlal Nehru, officially inaugurated the three-tier system of local rural self-government at Nagaur district in Rajasthan. This historic event marked the practical realization of Article 40 of the Directive Principles of State Policy, which commands the state to organize village panchayats and endow them with such powers and authority as may be necessary to enable them to function as units of self-government.`,
  `The conceptual architecture of democratic decentralization in India was formulated by the Balwant Rai Mehta Committee, appointed by the National Development Council in 1957. The committee recommended an organically linked, three-tier institutional structure comprising the Gram Panchayat at the village level, the Panchayat Samiti at the block level, and the Zila Parishad at the district level. Rajasthan proactively embraced these visionary recommendations by enacting the historic Rajasthan Panchayat Samitis and Zila Parishads Act in 1959. Andhra Pradesh soon followed suit, but Rajasthan earned the everlasting distinction of being the first state to transfer genuine executive powers, developmental funds, and administrative authority to elected rural representatives.`,
  `To strengthen grassroots democracy and remedy administrative deficiencies, several high-powered committees subsequently reviewed local governance frameworks, including the Ashok Mehta Committee in 1977, the G. V. K. Rao Committee in 1985, and the L. M. Singhvi Committee in 1986. The landmark 73rd Constitutional Amendment Act of 1992 imparted enduring constitutional status to Panchayati Raj Institutions (PRIs) by inserting Part IX and the Eleventh Schedule into the Indian Constitution, specifying twenty-nine distinct developmental subjects transferred to rural local bodies, such as agriculture, minor irrigation, drinking water, rural housing, and poverty alleviation programs.`,
  `In Rajasthan, the Panchayati Raj framework is governed by the Rajasthan Panchayati Raj Act of 1994 and its accompanying statutory rules. The state has been at the forefront of progressive electoral reforms, introducing affirmative reservations for Scheduled Castes, Scheduled Tribes, and Other Backward Classes, alongside a historic fifty percent reservation for women across all tiers of local bodies. Furthermore, the mandatory convening of the Ward Sabha and Gram Sabha ensures direct citizen participation, social audit of developmental expenditures, transparent selection of welfare beneficiaries, and scrutiny of public works executed under the Mahatma Gandhi National Rural Employment Guarantee Scheme (MGNREGS).`,
  `For clerical staff working within the Panchayati Raj and Rural Development Department, Zila Parishads, and Panchayat Samitis, administrative responsibilities are multifaceted and impactful. Lower Division Clerks process development sanction orders, maintain cashbooks, audit expenditure vouchers, update the e-Gram Swaraj national portal, and assist Village Development Officers (VDOs) and Block Development Officers (BDOs). Thorough knowledge of statutory financial rules, tender procurement processes, muster roll verification, and public grievance mechanisms enables clerical personnel to uphold fiscal transparency and prevent leakages in rural welfare delivery.`,
  `Modern Panchayati Raj governance in Rajasthan increasingly leverages digital public infrastructure, such as the Jan Soochna Portal and geospatial planning tools, to ensure real-time tracking of asset creation in rural habitations. Empowering elected representatives through structured training programs conducted by the Indira Gandhi Panchayati Raj and Gramin Vikas Sansthan (IGPRS) in Jaipur fosters administrative leadership among rural women and marginalized communities. Grassroots local self-government remains the lifeblood of rural empowerment, poverty reduction, and participative democracy across the desert and tribal villages of Rajasthan.`,
  `The social audit mechanisms instituted across Rajasthan Panchayati Raj bodies serve as a national paradigm for democratic accountability. Public hearings, citizen information display boards on Panchayat Bhavan walls, and real-time public portal updates allow rural residents to scrutinize work approvals and wage payments directly. Ministerial staff ensure that audit reports, utilization certificates (UCs), and physical verification registers are rigorously scrutinized before grant installments are disbursed under central and state finance commissions.`
]);

// 8. Major River Basins and Water Bodies of Rajasthan
addLesson(8, "Exercise : 8/100 - Major River Basins and Water Bodies of Rajasthan", "Rajasthan Geography", [
  `Due to its unique physical geography, prominent central Aravalli ridge, and distinct climatic zones, Rajasthan features a complex hydrological drainage network divided into three major categories: rivers flowing eastward to drain into the Bay of Bengal, rivers flowing westward or southward to drain into the Arabian Sea, and an extensive network of inland drainage streams that disappear into desert sands. Accounting for nearly 10.4 percent of India total geographical area, Rajasthan possesses barely 1.16 percent of the country total surface water resources, making scientific watershed management, river basin conservation, and reservoir management matters of critical administrative priority.`,
  `The Bay of Bengal drainage system is spearheaded by the Chambal river, the only perennial river of Rajasthan. Originating from the Singar Chauri peak in the Janapav hills of Madhya Pradesh, the Chambal enters Rajasthan near Chaurasigarh in Chittorgarh district, flowing through Kota, Bundi, Sawai Madhopur, Karauli, and Dholpur before merging with the Yamuna in Uttar Pradesh. Renowned for its dramatic gorges and deep ravines, the Chambal river system hosts the monumental Chambal Valley Hydroelectric Project, comprising four major dams: Gandhi Sagar in Madhya Pradesh, Rana Pratap Sagar at Rawatbhata, Jawahar Sagar, and the Kota Barrage. Its primary left-bank tributary, the Banas river—traditionally called 'Van Ki Asha' or Hope of the Forest—originates in the Khamnore hills near Kumbhalgarh, flowing entirely within Rajasthan for about five hundred twelve kilometres before joining the Chambal at Rameshwaram Ghat.`,
  `The Arabian Sea drainage system comprises the Luni, Sabarmati, and Mahi rivers. The Luni river is the lifeline of the arid western Thar Desert, originating in the Nag Pahar hills near Ajmer as the Sagarmati. It flows southwest through Nagaur, Jodhpur, Pali, Barmer, and Jalore before discharging into the Rann of Kutch in Gujarat. A unique hydrological characteristic of the Luni is that its water remains sweet and potable up to Balotra in Barmer, after which it turns highly saline due to excessive salt deposits in the desert soil. The Mahi river originates from the Vindhyan hills in Madhya Pradesh, traverses Banswara and Pratapgarh in a distinct U-shaped curve that crosses the Tropic of Cancer twice, and flows into the Gulf of Khambhat, impounded by the massive Mahi Bajaj Sagar Dam.`,
  `Inland drainage covers nearly sixty percent of Rajasthan territory, where seasonal streams lack sufficient gradient and water volume to reach the sea. Prominent inland rivers include the Kantli flowing through Sikar and Jhunjhunu, the Sabi originating in the Sewar hills of Jaipur, the Ruparel flowing through Alwar and Bharatpur, and the Ghaggar river in the north. The Ghaggar, often identified with the ancient Vedic river Saraswati, originates in the Shivalik hills of Himachal Pradesh and flows through Hanumangarh and Sri Ganganagar, occasionally reaching Fort Abbas in Pakistan during heavy monsoon flash floods.`,
  `Rajasthan is also adorned with historic freshwater and saline lakes that have supported civilizations for millennia. Sambhar Salt Lake, located at the intersection of Jaipur, Nagaur, and Ajmer, is India largest inland saline lake and a designated Ramsar wetland site, producing approximately nine percent of the nation total salt. Pristine freshwater lakes such as Lake Pichola, Fateh Sagar, Jaisamand (Dhebar Lake), Rajsamand, Ana Sagar in Ajmer, and Nakki Lake in Mount Abu represent historic marvels of hydraulic engineering. Lower Division Clerks in the Water Resources Department, Public Health Engineering Department (PHED), and Revenue Department play an indispensable role in maintaining dam storage logs, canal water allocations, and flood emergency registers.`,
  `Effective river basin planning, inter-basin water transfers, and groundwater recharge programs are critical for the socio-economic future of Rajasthan. Administrative staff must ensure compliance with environmental flow norms, prevent illegal sand mining along dry riverbeds, and coordinate inter-departmental efforts under the State Water Policy to safeguard every precious drop of surface water for drinking, agriculture, and industry. Preserving these watercourses ensures sustainable ecological balance and agricultural survival.`
]);

// 9. Folk Dances and Performing Arts of Rajasthan
addLesson(9, "Exercise : 9/100 - Folk Dances and Performing Arts of Rajasthan", "Art & Culture", [
  `The vibrant cultural soul, colourful social tapestry, and artistic genius of Rajasthan are vividly expressed through its rich repertoire of folk dances, theatrical performances, and musical traditions. Shaped by diverse royal patronages, desert nomadic traditions, spiritual devotion, and pastoral festivities, Rajasthani folk dances represent an extraordinary synthesis of graceful body movements, rhythmic footwork, dazzling traditional attire, and captivating percussion music. These performing arts have earned worldwide admiration and institutional recognition, serving as living treasures of India intangible cultural heritage.`,
  `Ghoomar is widely celebrated as the state dance of Rajasthan and the crown jewel of its performing arts. Traditionally performed exclusively by women on auspicious festivals such as Gangaur and Teej, Ghoomar derives its name from 'Ghoomna', referencing the graceful circular twirling movements of the dancers. Donning brightly coloured flowing skirts known as Ghaghras and shimmering Odhnis, dancers execute synchronized pirouettes, rhythmic hand clapping, and graceful wrist inflections to the accompaniment of traditional instruments like the Dhol, Nagada, and Shehnai. Historically nurtured within the royal palaces of Rajput royalty, Ghoomar has transcended courtly origins to become an integral element of celebratory social gatherings across all strata of Rajasthani society.`,
  `In 2010, the Kalbelia folk dance and songs of Rajasthan were inscribed on the Representative List of the Intangible Cultural Heritage of Humanity by UNESCO. Performed by the Kalbelia snake-charmer community, the dance is famous for its breathtaking serpentine flexibility, electrifying tempo, and acrobatic brilliance. Dressed in striking black embroidered flared garments adorned with mirror work and silver thread, female dancers imitate the fluid, rhythmic gliding movements of a serpent. The musical accompaniment is driven by the haunting drone of the Poongi (traditional wind instrument), supported by the Daf, Khanjari, and Dholak. Renowned folk artists such as Gulabo Sapera have showcased Kalbelia dance on prestigious global stages, bringing international acclaim to Rajasthan folk traditions.`,
  `Rajasthan is also famous for thrilling occupational and regional folk dances. The Chari dance of Kishangarh, practiced predominantly by the Gujjar community, features women balancing brass pots with burning cotton seeds on their heads while executing delicate foot movements. The Terah Taali dance, performed by women of the Kamada community during the sacred fair of Baba Ramdevji, is a mesmerizing devotional spectacle where dancers tie thirteen brass cymbals (Manjeeras) to their bodies and strike them in rapid rhythmic harmony while performing intricate domestic chores and holding swords in their teeth. In the Shekhawati region, the energetic Gindar dance and Chang dance dominate Holi festivities, while the Bhil tribe of Mewar performs the ancient ritualistic Gauri dance drama.`,
  `The Fire dance (Agni Nritya), executed by the Jasnathi sect in Bikaner, presents an awe-inspiring spectacle where devout ascetics dance barefoot over glowing embers of burning wood to the rhythmic chants of 'Fateh Fateh'. From an administrative and cultural governance standpoint, the Department of Art and Culture, the Rajasthan Sangeet Natak Akademi, and the West Zone Cultural Centre (WZCC) at Udaipur play a crucial role in preserving these folk arts. Clerks and administrative officers manage artist welfare schemes, process pension files for senior folk artists, organize state cultural festivals, and facilitate international cultural exchange delegations.`,
  `Preserving and promoting traditional performing arts provides sustainable livelihood opportunities for rural folk musicians, hereditary bards (Manganiyars and Langas), and tribal performers. Incorporating folk performances into heritage tourism circuits, desert festivals, and state ceremonial functions reinforces regional identity, enriches cultural tourism, and preserves the vibrant artistic traditions of Rajasthan for future generations. These performing traditions remain an enduring source of inspiration and cultural pride.`
]);

// 10. E-Governance and Jan Soochna Portal in Rajasthan
addLesson(10, "Exercise : 10/100 - E-Governance and Jan Soochna Portal in Rajasthan", "E-Governance", [
  `The state of Rajasthan has emerged as a visionary pioneer in the nationwide digital governance revolution by fundamentally transforming public administration through transparent, accountable, and citizen-centric information technology systems. Modern e-governance seeks to replace traditional bureaucratic hurdles, physical paperwork, and manual delays with seamless, automated, and paperless public service delivery. The Department of Information Technology and Communication (DoIT&C) has architected an extensive digital ecosystem designed to bring government services directly to the doorsteps of millions of citizens across urban cities and remote rural panchayats.`,
  `A monumental milestone in Rajasthan digital transparency journey is the landmark launch of the Jan Soochna Portal in September 2019. Conceptualized as an unprecedented institutional mechanism under Section 4(2) of the Right to Information Act 2005, the Jan Soochna Portal mandates the proactive, suo motu disclosure of government information in the public domain. Unlike traditional RTI procedures that require citizens to submit written applications, pay fees, and wait thirty days for replies, the Jan Soochna Portal empowers any citizen to instantly access comprehensive public welfare data online without filing any application. Today, the portal hosts real-time information on hundreds of government schemes across dozens of departments, covering public distribution rations, social security pensions, MGNREGS job cards, land records, and mining leases.`,
  `Complementing the Jan Soochna Portal is the Rajasthan Single Sign-On (RajSSO) digital identity framework, which provides a unified, secure authentication gateway for citizens, government employees, and business enterprises. Through a single SSO ID, users can seamlessly access an extensive suite of administrative applications, including RajKaj (integrated enterprise office workflow), e-Mitra (citizen service delivery platform), Shala Darpan (school education monitoring), and the Integrated Financial Management System (IFMS). For government employees, RajKaj has digitized the entire lifecycle of official correspondence, including file tracking, electronic noting, annual performance appraisal reports (APAR), leave applications, and property return submissions.`,
  `The e-Mitra digital delivery network represents one of the largest public-private partnership (PPP) service networks in India. With tens of thousands of active kiosks operating across every gram panchayat and urban ward, e-Mitra enables citizens to pay electricity and water bills, apply for caste and domicile certificates, register births and deaths, and enroll in government welfare schemes without visiting government offices. This decentralized digital infrastructure eliminates intermediaries, curtails administrative corruption, and ensures equitable access to essential public utilities for vulnerable rural populations.`,
  `For Lower Division Clerks (LDCs) and junior administrative officers in Rajasthan government secretariats, mastery of e-governance platforms is indispensable for daily office workflows. Clerks must efficiently process electronic files on RajKaj, verify digital signatures, manage secure citizen databases, validate Aadhaar and Jan Aadhaar beneficiary credentials, and monitor online grievances registered on the Rajasthan Sampark portal. Prompt file disposal, accurate electronic indexing, and timely redressing of citizen complaints are monitored through automated digital dashboards reviewed directly by District Collectors and the Chief Secretary.`,
  `By fostering transparency, eliminating bureaucratic opacity, and democratizing access to public information, Rajasthan digital governance initiatives have set a national benchmark for responsive democratic administration. Sustained investment in digital literacy, rural broadband connectivity via RajNET, and cyber security safeguards will ensure that e-governance continues to empower citizens and elevate administrative productivity to global standards. Digital transparency fundamentally transforms state administration into an accountable, public-first governance system.`
]);

// 11. Operating Systems and Graphical User Interfaces
addLesson(11, "Exercise : 11/100 - Operating Systems and Graphical User Interfaces", "Computer Fundamentals", [
  `An Operating System (OS) is the foundational system software that manages computer hardware resources, coordinates peripheral devices, and provides common services for application programs. In government administration and office automation, operating systems provide the crucial operational interface between clerical personnel and computational machinery. Without an operating system, computer hardware remains an inert assemblage of electronic circuits incapable of executing word processing tasks, financial spreadsheets, or official correspondence workflows. Mastering operating system fundamentals, memory allocation, process scheduling, and user interface navigation is indispensable for modern ministerial staff.`,
  `Historically, operating systems evolved from early single-tasking command-line interfaces (CLI) such as MS-DOS to sophisticated modern Graphical User Interfaces (GUI) like Microsoft Windows, Linux distributions (including Ubuntu and BOSS Linux developed for Indian governance), and macOS. While a command-line interface requires users to memorize and execute precise textual commands such as DIR, COPY, or CHKDSK, a Graphical User Interface leverages visual metaphors including windows, icons, menus, and pointers (WIMP). GUIs dramatically accelerate clerical productivity by allowing staff to open multiple application windows simultaneously, drag and drop documents between directories, and execute functions effortlessly using a mouse or touchscreen.`,
  `The core architectural component of any operating system is the Kernel, which resides permanently in primary memory once booted. The kernel directly interfaces with the CPU, allocating execution time slices through sophisticated process management algorithms such as First-Come-First-Served, Round Robin, and Priority Scheduling. Additionally, the operating system oversees memory management through virtual memory techniques and paging, ensuring that demanding software suites do not crash when physical RAM capacity is exceeded. The file system manager organizes digital records into logical directory hierarchies, enforcing access control permissions and formatting storage drives using file systems such as NTFS, FAT32, or ext4.`,
  `In state secretariats and district offices across Rajasthan, operating system security and configuration maintenance form essential clerical duties. Clerical users must know how to navigate the Control Panel and Settings app, manage device drivers via Device Manager, terminate frozen background processes through the Task Manager, and configure local network adapters. Government IT policies mandate regular operating system patch installations, automated Windows Defender updates, and user account privilege separation to safeguard public records against malware infections, ransomware lockouts, and unauthorized data extraction.`,
  `Furthermore, the adoption of open-source operating systems like BOSS (Bharat Operating System Solutions) in specialized defense and public administration sectors highlights the importance of platform adaptability. Clerks must be versatile in working across heterogeneous operating environments, configuring regional language fonts such as Devnagari in Unicode, and backing up system state files. A comprehensive grasp of operating system mechanics enables clerical staff to resolve routine desktop glitches independently, maintain continuous office workflow, and protect administrative databases with vigilance.`,
  `Effective file organization on local hard drives and mapped network shares prevents loss of critical administrative records. Clerks must follow standardized file naming conventions, establish structured directory hierarchies for annual budget proposals, cabinet memorandums, and departmental audit replies, and execute regular disk defragmentation and cleanup routines. Maintaining an optimized operating system environment enhances computational responsiveness and ensures uninterrupted public service delivery.`
]);

// 12. Rajasthan Renewable and Solar Energy Revolution
addLesson(12, "Exercise : 12/100 - Rajasthan Renewable and Solar Energy Revolution", "Economy & Energy", [
  `Blessed with an abundance of intense solar insolation, vast expanses of barren arid land, and more than three hundred twenty-five clear sunny days annually, the state of Rajasthan has spearheaded India renewable clean energy transition. The state has emerged as the unchallenged solar capital of the nation, boasting the largest installed solar power generation capacity in India and pioneering monumental mega-scale solar park developments. This clean energy transformation is pivotal for addressing global climate change commitments, reducing dependence on carbon-intensive thermal power, generating substantial industrial investment, and fostering green employment across desert districts.`,
  `The cornerstone of Rajasthan solar leadership is the world-renowned Bhadla Solar Park, situated in the Phalodi district (formerly part of Jodhpur). Spanning over fourteen thousand acres across inhospitable desert terrain, the Bhadla Solar Park has an operational capacity exceeding two thousand two hundred megawatts, making it one of the largest single-location solar power clusters in the entire world. The park combines state-of-the-art photovoltaic technologies, automated robotic solar panel cleaning systems that operate without wasting scarce desert water, and ultra-high-voltage transmission corridors that export clean electricity across national power grids to industrial centers in northern and western India.`,
  `To accelerate clean energy deployment, the state government formulated the comprehensive Rajasthan Solar Energy Policy and the Wind and Hybrid Energy Policy. These progressive policy frameworks offer lucrative incentives to private renewable developers, including single-window clearance, land allotment on concessional lease terms through the Rajasthan Renewable Energy Corporation Limited (RRECL), stamp duty exemptions, and streamlined electricity grid connectivity. Major industrial conglomerates and public sector undertakings, such as NTPC, SECI, and private green energy giants, have established multi-gigawatt solar farms in Jaisalmer, Bikaner, Jodhpur, and Barmer.`,
  `Beyond large-scale utility solar parks, Rajasthan has proactively implemented decentralized solar initiatives such as the PM-KUSUM (Pradhan Mantri Kisan Urja Suraksha evam Utthaan Mahabhiyan) scheme. Component A and Component B of PM-KUSUM empower rural farmers to install solar-powered agricultural water pumps and setup small solar power plants on barren agricultural land, enabling them to generate supplemental agricultural income by feeding surplus power into rural feeder grids. Rooftop solar subsidies in urban municipalities have further democratized renewable energy adoption, reducing domestic electricity tariffs and easing peak summer grid strains.`,
  `For administrative officers and ministerial clerks in the Energy Department, RRECL, and district collectorates, the solar boom requires diligent record-keeping regarding land acquisition, lease deeds, transmission line right-of-way permissions, environmental clearances, and power purchase agreements (PPAs). Clerks must verify subsidy disbursement claims under rooftop solar schemes, process online developer applications through single-window portals, and compile monthly renewable generation statistics for state and national monitoring bodies. Rajasthan clean energy revolution stands as a global testament to transforming geographic climatic adversity into infinite sustainable prosperity.`,
  `Integrating green hydrogen production and battery energy storage systems (BESS) represents the next frontier in Rajasthan clean energy roadmap. Harnessing daytime solar surplus to power electrolyzers for green ammonia and hydrogen manufacturing positions desert districts as premier hubs of future green industrial manufacturing. Rigorous administrative oversight ensures timely project commissioning, environmental safety compliance, and equitable benefit distribution to local rural communities.`
]);

// 13. Mineral Resources and Mining Industry of Rajasthan
addLesson(13, "Exercise : 13/100 - Mineral Resources and Mining Industry of Rajasthan", "Economy & Minerals", [
  `Geologically endowed with extraordinarily diverse rock formations spanning from the Archaean era to recent alluvium, Rajasthan is popularly referred to as the 'Museum of Minerals'. The state possesses immense geological wealth, producing over eighty-one distinct minerals, of which fifty-seven are commercially exploited on a large scale. Rajasthan holds a virtual national monopoly in the production of vital strategic and industrial minerals such as lead-zinc, wollastonite, calcite, selenite, and gypsum, while contributing substantially to the national output of copper, rock phosphate, silver, marble, and sandstone. The mining industry represents a pivotal driver of the state economy, generating extensive industrial employment and substantial revenue for the state exchequer.`,
  `The Aravalli geological province hosts world-class base metal deposits. The Rampura Agucha mine in Bhilwara district, operated by Hindustan Zinc Limited, is recognized as one of the largest and richest open-pit zinc-lead deposits globally. In Rajsamand district, the Rajpura Dariba and Sindesar Khurd underground mines contribute massive volumes of silver and lead-zinc concentrates. In Jhunjhunu district, the historic Khetri Copper Complex has been mined since the Indus Valley Civilization, continuing to produce valuable copper ores under the management of Hindustan Copper Limited. In Udaipur, the Jhamarkotra rock phosphate mines represent India foremost domestic source of raw material for chemical fertilizer manufacturing.`,
  `In addition to metallic and industrial minerals, Rajasthan is world-famous for its dimensional building stones. The pristine white marble of Makrana in Nagaur was historically used to construct the immortal Taj Mahal in Agra and the Victoria Memorial in Kolkata. Granites of Jalore, sandstones of Jodhpur, Dholpur, and Karauli, slate stones of Alwar, and the famous Kota stone from Ramganj Mandi form the bedrock of India architectural construction materials. In western Rajasthan, extensive deposits of lignite coal in Bikaner and Barmer fuel pit-head thermal power plants, while vast bentonite and fuller earth reserves support chemical processing industries.`,
  `The Department of Mines and Geology, headquartered in Udaipur, governs mineral exploration, lease auctions, and regulatory enforcement across Rajasthan. In recent years, the state has transitioned towards transparent electronic auctions (e-auctions) for major and minor mineral concessions, in strict conformity with the Mines and Minerals (Development and Regulation) Act (MMDR Act). To redress environmental degradation and assist local mining-affected communities, the state established the District Mineral Foundation Trust (DMFT), funded by statutory mining royalties to finance rural drinking water, healthcare, education, and road infrastructure in mining belts.`,
  `Ministerial staff and clerks in mining department field offices, treasury directorates, and collectorates handle critical documentation, including processing royalty collection contracts, tracking mineral transit passes (e-Ravanna), auditing DMF trust accounts, and coordinating anti-illegal mining vigilance task forces. Mastery of mining laws, royalty calculation formulas, and environmental clearance verification ensures that mineral exploitation contributes sustainably to state industrial prosperity without compromising ecological integrity or public safety.`,
  `Recent discoveries of rare earth elements (REE) in Barmer and Jalore, alongside substantial potash deposits in the Hanumangarh-Bikaner basin, offer exciting avenues for future industrial expansion. Efficient administrative management of mineral concessions, strict implementation of mine safety regulations, and environmental reclamation of abandoned quarries ensure that Rajasthan mining wealth continues to enrich future generations sustainably.`
]);

// 14. Freedom Struggle and Prajamandal Movements
addLesson(14, "Exercise : 14/100 - Freedom Struggle and Prajamandal Movements", "Rajasthan History", [
  `The saga of India struggle for national independence was matched in the princely states of Rajputana by heroic mass movements against feudal oppression, autocratic taxation, and British colonial exploitation. While the mainstream national freedom movement led by Mahatma Gandhi and the Indian National Congress fought directly against British rule in British India, the citizens of Rajasthan princely states faced a dual burden: the autocratic rule of local princely rulers and Jagirdars on one hand, and the overarching imperial suzerainty of the British Crown on the other. This double exploitation catalyzed the historic Prajamandal movements and peasant uprisings that democratized the state.`,
  `The peasant movements of Rajasthan ignited the spirit of mass resistance across the region. Foremost among them was the Bijolia Peasant Movement in Mewar (Bhilwara district), recognized as the longest peaceful, non-violent peasant struggle in Indian history, lasting from 1897 to 1941. Sparked by eighty-four extortionate feudal levies (Lag-Bagh) and forced unpaid labour (Begar) imposed on peasants by the local Thikana, the movement was championed by legendary leaders such as Sadhu Sitaram Das, Vijay Singh Pathik (Bhup Singh), and Manikya Lal Verma. Vijay Singh Pathik organized the peasants through the Rajasthan Seva Sangh and nationalized the struggle through his newspaper 'Pratap', published from Kanpur by Ganesh Shankar Vidyarthi.`,
  `Simultaneously, inspiring peasant uprisings erupted across other princely domains. The Bengu Peasant Movement under Ramnarayan Choudhary witnessed the supreme martyrdom of Rupa Ji and Kripa Ji Dhakad during a police firing in 1923. In Alwar, the brutal Neemuchana massacre of May 14, 1925, where colonial state forces opened fire on peacefully protesting farmers, was condemned by Mahatma Gandhi as 'Dyrism Double Distilled'. In Shekhawati, the Jat peasant agitations against feudal Jagirdars culminated in the historic Katrathal Women Conference in 1934, where over ten thousand peasant women gathered under the fearless leadership of Kishori Devi to assert their dignity and rights.`,
  `To demand responsible democratic government under the aegis of the rulers, political organizations called Prajamandals were established across Rajasthan during the 1930s. The Jaipur Prajamandal was founded in 1931 by Kapoorchand Patni and revitalized in 1936 by Jamnalal Bajaj and Hiralal Shastri. The Marwar Lok Parishad was established in Jodhpur under the guidance of Jai Narayan Vyas. The Mewar Prajamandal was formed in 1938 by Manikya Lal Verma, while freedom fighters like Gokulbhai Bhatt established the Sirohi Prajamandal and Magharam Vaid founded the Bikaner Prajamandal. Despite severe police atrocities, detentions, and newspaper bans, Prajamandal activists organized civil disobedience, spread adult literacy, fostered khadi spinning, and demanded civil liberties.`,
  `The sacrifice of freedom fighters such as Sagar Mal Gopa of Jaisalmer—who was burned alive in prison in 1946 for exposing feudal tyranny in his book 'Jaisalmer Ka Gundaraj'—galvanized national public outrage and accelerated the collapse of feudal rule. Understanding the heroic sacrifices, constitutional resolutions, and institutional transitions of the Prajamandal movements is vital for administrative civil servants. Clerical staff in the General Administration Department process freedom fighter family pension files, preserve archival historical gazettes, and manage state memorial museums. The bravery of these grassroots patriots laid the democratic foundation upon which modern democratic Rajasthan was erected.`,
  `The legacy of the Prajamandal movement continues to inspire modern democratic values across Rajasthan. The fearless resolve of these grassroots leaders dismantled age-old feudal privileges, liberated marginalized agrarian communities from bonded servitude, and established the supremacy of fundamental rights. Preserving the historical documentation and personal correspondence of these visionary patriots provides administrative candidates with an enduring appreciation for constitutional liberty and social justice.`
]);

// 15. Microsoft Word and Document Formatting in Office
addLesson(15, "Exercise : 15/100 - Microsoft Word and Document Formatting in Office", "Computer Applications", [
  `Microsoft Word is the global benchmark word processing application utilized across government secretariats, public sector undertakings, and corporate organizations for drafting, formatting, editing, and publishing official documents. In the day-to-day administrative workflow of a Lower Division Clerk (LDC) or Junior Assistant, proficiency in Microsoft Word is indispensable. Ministerial staff rely on Word to prepare official gazette notifications, cabinet memorandums, executive sanctions, semi-official (DO) letters, office memorandums, and citizen grievance responses. Understanding the comprehensive feature set of modern word processors ensures that official documentation conforms to rigid administrative standards of legibility, visual hierarchy, and security.`,
  `The user interface of Microsoft Word is built around the Ribbon system, which organizes functional commands into intuitive contextual tabs such as Home, Insert, Page Layout, References, Mailings, Review, and View. The Home tab provides essential text typography controls, enabling users to adjust font families (such as Arial, Times New Roman, or Kruti Dev and Mangal for bilingual Hindi-English documentation), font sizes, bold, italic, underline attributes, subscript, and superscript. Clerks must master paragraph formatting options, including left, right, center, and justified text alignment, line spacing (such as single, 1.15, or double line spacing), paragraph indentations, and customized bulleted or numbered hierarchical lists.`,
  `Page layout configuration is paramount when drafting official communications that must be printed on official letterheads or archived in legal binders. The Page Layout tab allows clerks to configure page orientation (portrait for standard letters and landscape for wide tabular statements), page sizes (such as A4 or Legal), and custom margins (typically one-inch top, bottom, left, and right margins, with an additional gutter margin on the left for file binding). Inserting headers and footers with automated page numbering in formats like 'Page X of Y', department file tracking numbers, and confidential classification stamps ensures accountability across multi-page government reports.`,
  `Another powerful feature essential for ministerial productivity is Mail Merge, located on the Mailings tab. Mail Merge enables a clerk to generate hundreds of personalized official notices, exam admit cards, or meeting convocations by merging a standardized master document with an external structured data source, such as an Excel spreadsheet or database file. Instead of typing individual letters manually, Mail Merge automatically populates dynamic merge fields (such as Citizen Name, Address, Application Number, and Hearing Date), drastically reducing clerical workload and eliminating transcription errors.`,
  `In addition, ministerial personnel must utilize the Review tab for collaborative document vetting. Features such as Track Changes, Insert Comments, and Document Comparison allow senior supervisory officers (like Section Officers or Deputy Secretaries) to review draft proposals, suggest modifications, and accept or reject edits transparently. Utilizing built-in Spell Check, Thesaurus, AutoCorrect rules, and Document Protection (restricting editing or encrypting with passwords) ensures that government files remain linguistically immaculate and legally secure. Mastering these practical Microsoft Word capabilities empowers clerical staff to execute administrative correspondence with high speed, aesthetic precision, and executive excellence.`,
  `Furthermore, mastering table formatting within Word is vital for presenting statistical data, budgetary allocations, and staff seniority rosters. Clerks must know how to merge and split table cells, adjust column widths proportionally, repeat header rows across page breaks, and convert text into tables seamlessly. Converting finalized Word documents into standardized PDF format protects formatting integrity across different operating systems and ensures audit-ready digital archiving.`
]);

// 16. Wildlife Conservation and National Parks in Rajasthan
addLesson(16, "Exercise : 16/100 - Wildlife Conservation and National Parks in Rajasthan", "Environment & Wildlife", [
  `Rajasthan boasts an extraordinary ecological biodiversity that defies its common stereotype as merely an arid desert wasteland. Spanning across diverse biogeographical zones—from the lush, subtropical deciduous forests of the Vindhyan and Aravalli ranges to the thorny scrublands and arid dune expanses of the Great Indian Thar Desert—the state provides critical sanctuary for some of the rarest and most magnificent wildlife species on Earth. The state forest department, alongside dedicated local wildlife communities like the Bishnois, has established an extensive protected area network comprising five National Parks, dozens of Wildlife Sanctuaries, and numerous Conservation Reserves dedicated to protecting fragile ecosystems.`,
  `The crown jewel of tiger conservation in northern India is Ranthambore National Park, situated in Sawai Madhopur district at the picturesque junction of the Aravalli and Vindhyan mountain ranges. Dominated by the historic tenth-century Ranthambore Fort, the park is world-renowned for its healthy, diurnal Royal Bengal Tiger population, thriving amidst an undulating landscape of dhok forests, rugged rocky ridges, and historic water reservoirs like Padam Talao and Rajbagh Lake. Legendarily home to iconic tigers like Machhli, Ranthambore has served as an essential nursery for restocking other protected reserves, such as Sariska Tiger Reserve in Alwar, where tigers were successfully reintroduced after facing severe poaching crises in the early 2000s.`,
  `In eastern Rajasthan, Keoladeo National Park in Bharatpur represents a globally acclaimed avian wonderland and a designated UNESCO World Heritage Site and Ramsar wetland. Formerly known as the Bharatpur Bird Sanctuary, this artificial, man-managed wetland was historically developed by the Maharajas of Bharatpur as a duck-hunting preserve, fed by the Ajan Dam and Gambhir river. Today, Keoladeo hosts over three hundred seventy species of resident and migratory waterbirds, serving as a vital winter feeding ground for aquatic birds migrating along the Central Asian Flyway from Siberia, Central Asia, and China, including painted storks, pelicans, cranes, and rare waterfowl.`,
  `In the arid west, Desert National Park, sprawling across Jaisalmer and Barmer districts over more than three thousand square kilometres, is the ultimate stronghold of the Great Indian Bustard (Godawan), the critically endangered state bird of Rajasthan. With fewer than one hundred fifty individuals surviving in the wild due to habitat fragmentation and power line collisions, intensive conservation initiatives—such as artificial captive breeding centers at Sam and Ramdevra—are underway to pull this majestic bird back from the brink of extinction. The park is also home to desert foxes, chinkaras (Indian gazelles), blackbucks, and prehistoric wood fossil remains at Akal Wood Fossil Park dating back one hundred eighty million years to the Jurassic era.`,
  `For administrative staff in the Forest and Environment Department and District Collectorates, wildlife administration involves handling critical files regarding wildlife census operations, eco-tourism concession tenders, forest boundary demarcations, crop compensation claims for wild animal depredation, and anti-poaching prosecution dossiers under the Wildlife Protection Act 1972. Preserving Rajasthan pristine wilderness corridors balances economic revenue from global eco-tourism with ecological stability and ethical stewardship of our natural heritage.`,
  `Community-led conservation movements, particularly inspired by the spiritual ethos of the Bishnoi community who consider animal and tree protection sacred duty, reinforce state enforcement efforts. The Mukundra Hills Tiger Reserve in Hadoti and the newly notified Ramgarh Vishdhari Tiger Reserve in Bundi further expand protected wildlife corridors. Sustainable wildlife conservation requires diligent administrative oversight, habitat restoration, and active community participation across all forest divisions.`
]);

// 17. Agriculture and Major Crops of Rajasthan
addLesson(17, "Exercise : 17/100 - Agriculture and Major Crops of Rajasthan", "Agriculture & Economy", [
  `Agriculture and allied pastoral activities constitute the socioeconomic lifeline of Rajasthan, sustaining over sixty-five percent of its population and contributing significantly to the Gross State Domestic Product (GSDP). Despite immense climatic challenges, including erratic monsoon precipitation, extensive arid soils, and severe groundwater depletion, the resilience of Rajasthani farming communities, backed by modern agronomic practices and expanding canal irrigation, has established the state as a major agrarian powerhouse in India. Rajasthan is divided into ten distinct agro-climatic zones, enabling the cultivation of an extensive variety of food grains, commercial oilseeds, fiber crops, and high-value arid horticulture.`,
  `The agricultural cropping pattern of Rajasthan is divided into two primary seasonal cycles: the Kharif (monsoon) season and the Rabi (winter) season, alongside a minor Zaid (summer) inter-crop season. Kharif crops are sown with the onset of the southwest monsoon in June and July and harvested in September and October. The dominant Kharif staple of western Rajasthan is Bajra (Pearl Millet), in which Rajasthan ranks first in the entire country in terms of both area and production. Bajra is exceptionally drought-hardy, requiring minimal moisture while providing nutrient-dense food for human consumption and nutritious fodder for livestock. Other major Kharif crops include Moth bean, Moong bean, Guar (Cluster bean), Sesame (Til), Soybean in the Hadoti belt, Cotton in Sri Ganganagar, and Groundnut in Bikaner.`,
  `The Rabi season commences in October and November, with harvesting taking place in March and April. Rabi cultivation relies on residual soil moisture, canal networks, and tube-well irrigation. Rajasthan is the unchallenged national leader in the production of Rapeseed and Mustard, often referred to as yellow gold, with Bharatpur, Alwar, and Ganganagar acting as major processing hubs. Wheat is the leading food grain of the Rabi season, cultivated extensively in irrigated plains, alongside Barley, Gram (Chickpea), and Coriander in Kota and Baran. Furthermore, Rajasthan produces valuable seed spices, holding national monopolies in the cultivation of Cumin (Jeera) in Jalore and Barmer, Fenugreek (Methi), Fennel (Saunf), and Isabgol (Psyllium husk).`,
  `To mitigate climatic vulnerabilities, the state government implements comprehensive agricultural support initiatives. The Pradhan Mantri Fasal Bima Yojana (PMFBY) provides financial safety nets against drought, unseasonal hailstorms, and pest infestations. Through the Mukhyamantri Kisan Mitra Urja Yojana, farmers receive subsidized electricity tariffs for agricultural pumps. The State Agriculture Department actively promotes micro-irrigation systems, distributing capital subsidies for drip and sprinkler irrigation units that conserve up to fifty percent of water while boosting crop yields. Soil testing laboratories across district Krishi Vigyan Kendras (KVKs) issue Soil Health Cards to guide balanced fertilizer application.`,
  `Ministerial staff in the Department of Agriculture, Revenue Collectorates, and Krishi Upaj Mandi Samitis (APMCs) manage extensive administrative records. Lower Division Clerks process crop damage compensation files (Girdawari assessments), verify direct benefit transfers (DBT) under PM-KISAN, audit Mandi fee collections, and assist in agricultural loan waiver implementations. An accurate, empathetic, and efficient clerical workforce ensures that government welfare allocations reach distressed agrarian households promptly, strengthening the rural economy and food security of Rajasthan.`,
  `Encouraging organic farming, precision agriculture, and protected greenhouse cultivation represents the modern roadmap for desert agriculture. Promoting farmer producer organizations (FPOs) enables small and marginal farmers to aggregate produce, negotiate better market prices, and eliminate exploitative middlemen. Integrating digital Mandi trading platforms through e-NAM connects Rajasthan farmers directly with national commodity markets, maximizing farm incomes and fostering agricultural prosperity.`
]);

// 18. Fairs and Festivals of Rajasthan
addLesson(18, "Exercise : 18/100 - Fairs and Festivals of Rajasthan", "Art & Culture", [
  `In Rajasthan, a land of legendary desert sands and heroic history, fairs and festivals are not merely calendar events; they are vibrant celebrations of life, spiritual devotion, seasonal rhythms, and community solidarity. The cultural calendar of the state is replete with magnificent traditional fairs (Melas) and cultural celebrations (Utsavs) that attract millions of pilgrims, rural folk, and international tourists throughout the year. These celebratory gatherings transform arid landscapes into kaleidoscopic spectacles of colourful traditional turbans (Safas), shimmering embroidered mirror-work skirts, rhythmic folk songs, camel competitions, and bustling rural trade marts.`,
  `Foremost among the sacred religious fairs is the Pushkar Fair, held annually in the holy town of Pushkar near Ajmer during the auspicious month of Kartik Purnima (October-November). Nestled around the sacred Pushkar Lake and home to one of the very few temples dedicated to Lord Brahma in the world, the fair is an extraordinary amalgamation of deep religious pilgrimage and the world largest camel and livestock trading fair. Hundreds of thousands of pilgrims take holy dips in the sacred Sarovar, while Rajasthani pastoralists buy and sell beautifully decorated camels, horses, and bullocks. The event features thrilling turban-tying competitions, traditional folk dances, and moustache contests that captivate international travellers.`,
  `In western Rajasthan, the Ramdevra Fair in Pokhran (Jaisalmer district) is a celebrated symbol of communal harmony and spiritual equality. Held during the Bhadrapada month, it commemorates the revered fourteenth-century folk deity Baba Ramdevji, who dedicated his life to eradicating untouchability and uplifting marginalized communities. Pilgrims from all religious faiths—Hindus, Muslims, and Sikhs—arrive on foot (Padayatris) singing devotional hymns and carrying colourful cloth flags (Neshans). Other prominent spiritual fairs include the Karni Mata Fair at Deshnoke near Bikaner, famous for thousands of revered white rats (Kabas), the Sheetla Mata Fair in Chaksu, and the Khatushyamji Fair in Sikar.`,
  `The tribal belts of southern Rajasthan celebrate the famous Beneshwar Fair in Dungarpur district at the sacred confluence (Triveni Sangam) of the Som, Mahi, and Jakham rivers. Revered as the 'Pushkar of the Tribals' or the 'Kumbh of the Bhils', the fair witnesses thousands of Bhil, Meena, and Garasia tribal pilgrims performing ancestral rites, immersing ashes, and worshipping the Svayambhu Shivlinga amidst vibrant musical dances and archery demonstrations. Additionally, modern cultural festivals organized by the Department of Tourism—such as the Desert Festival in Jaisalmer, the Marwar Festival in Jodhpur, the Camel Festival in Bikaner, and the Teej and Gangaur pageants in Jaipur—showcase royal heritage and artistic brilliance.`,
  `From an administrative standpoint, organizing these gigantic fairs requires complex inter-departmental coordination involving District Collectors, Police, Municipalities, Transport, and Health departments. Ministerial clerks in administrative offices draft temporary law and order duty orders, process licenses for fairground vendors, allocate public transport routes with RSRTC, manage sanitation contracts, and audit pilgrimage toll collections. Ensuring public safety, clean drinking water, and crowd control at these historic cultural congregations preserves Rajasthan hospitable tradition of 'Padharo Mhare Des'.`,
  `These fairs provide a vital boost to the rural economy, offering artisans, potters, blacksmiths, and folk performers a lucrative direct marketplace to sell their goods without middlemen. The vibrant social cohesion nurtured by shared participation in fairs and festivals transcends modern social divisions, reinforcing Rajasthan timeless identity as a land of cultural harmony, heroic legacy, and infectious celebration.`
]);

// 19. Official Noting and Drafting Protocols for Clerks
addLesson(19, "Exercise : 19/100 - Official Noting and Drafting Protocols for Clerks", "Office Procedures", [
  `Official noting and drafting constitute the fundamental instruments of communication, decision-making, and permanent record-keeping in government departments and secretariats across Rajasthan. Government business is conducted in writing to ensure constitutional accountability, procedural legality, financial propriety, and institutional transparency. Every decision sanctioning public expenditure, appointing administrative personnel, issuing executive circulars, or amending statutory rules must be anchored in meticulously documented file notes. For Lower Division Clerks (LDCs) and Junior Assistants, mastering the precise art of noting and drafting is the single most critical clerical qualification governing professional competence and career advancement.`,
  `An official file docket is structurally partitioned into two distinct halves: the 'Notes' portion on the left-hand side and the 'Correspondence' portion on the right-hand side. The Notes portion contains the chronological record of administrative discussions, rule analyses, precedent cross-referencing, and executive approvals leading up to a decision. The Correspondence portion holds incoming letters (Dak), government orders, petitions, and carbon copies of dispatched replies. Pages in both portions must be numbered consecutively in ink or digital sequence, and referencing between notes and correspondence must be executed through precise flags (e.g., Flag 'A', Flag 'B') to facilitate effortless perusal by higher authorities.`,
  `Official noting requires strict adherence to stylistic norms established in the Secretariat Manual of Office Procedure (SMOP). Notes must be written in courteous, objective, concise, and unambiguous language, strictly avoiding colloquial slang, emotional outbursts, or personal prejudices. A standard note drafted by a clerk typically comprises three core segments: first, a succinct statement of the case outlining the core problem or request; second, an objective factual analysis summarizing historical precedents, financial implications, and statutory provisions under the Rajasthan Service Rules (RSR) or General Financial and Accounts Rules (GF&AR); and third, clear, alternative actionable recommendations placed before the Section Officer, Assistant Secretary, or Head of Department for executive decision.`,
  `Drafting, on the other hand, represents the preparation of the outward official communication once the competent authority approves the note. Various standardized formats exist for government correspondence, each tailored for a specific administrative context: Official Letters for formal communications between different governments or external bodies; Office Memorandums (OM) for inter-departmental communications; Demi-Official (DO) letters written in personal first-person style by senior officers to draw urgent personal attention; Endorsements for forwarding documents with instructions; and Gazette Notifications for publishing statutory rules and appointments. Clerks must draft communications accurately, ensuring that subject headings, file numbers, date stamps, and recipient designations match the approved file notes exactly.`,
  `In the modern era of the RajKaj electronic office suite, traditional paper dockets have been transformed into digital e-Files. However, the intellectual rigour of noting and drafting remains identical. Clerks must master digital drafting interfaces, attach verifiable digital signatures, ensure PDF audit-trail integrity, and index electronic files systematically. Diligent, legally sound noting and drafting protect the government against unnecessary judicial litigation and audit objections, serving as the bedrock of transparent, efficient, and accountable democratic governance.`,
  `Furthermore, ministerial personnel must pay meticulous attention to grammatical precision, correct punctuation, and concise sentence structures when preparing official drafts. Ambiguous phrasing or vague recommendations can mislead decision-makers, delay urgent administrative approvals, or expose the department to costly legal challenges in the Rajasthan High Court. The ability to draft crystal-clear office notes is the hallmark of an exceptional civil servant.`
]);

// 20. Microsoft Excel and Spreadsheet Data Analysis
addLesson(20, "Exercise : 20/100 - Microsoft Excel and Spreadsheet Data Analysis", "Computer Applications", [
  `Microsoft Excel is a powerful, globally utilized electronic spreadsheet software application engineered for mathematical computation, statistical analysis, data visualization, and automated record-keeping. In public administration, treasury operations, and departmental secretariats across Rajasthan, Excel is an indispensable tool for ministerial staff and Lower Division Clerks. Clerks routinely leverage Excel to compile annual departmental budgets, prepare employee monthly salary bills, track social welfare scheme disbursements, analyze district census demographics, and generate audit-compliant financial reports. Developing advanced proficiency in spreadsheet functions, formula syntax, and data hygiene is essential for clerical productivity and administrative accuracy.`,
  `The structural foundation of Microsoft Excel consists of a workbook containing individual worksheets. Each worksheet is an extensive two-dimensional grid composed of vertical columns identified by alphabetical letters and horizontal rows identified by numerical digits. The intersection of a row and a column forms a Cell, designated by a unique coordinate address such as A1, B10, or F45. Cells can hold diverse data types, including plain text labels, numerical values, calendar dates, currency symbols, and dynamic mathematical formulas. Clerks must master basic cell formatting techniques, such as adjusting column widths, wrapping text, merging cells, and applying borders and shading to create clear, executive-ready tabular statements.`,
  `The true analytical power of Excel lies in its extensive repository of mathematical, logical, and lookup formulas. Every formula must begin with an equal sign (=). Fundamental mathematical operations include SUM (calculating totals), AVERAGE (determining arithmetic means), COUNT and COUNTA (tallying entries), and MIN and MAX (identifying extremes). For more complex administrative decision-making, clerks utilize conditional logic functions such as IF, AND, and OR, which evaluate whether specific criteria are met—for instance, determining whether a pensioner is eligible for enhanced dearness allowance. Furthermore, lookup functions like VLOOKUP, HLOOKUP, and the modern XLOOKUP allow users to search and extract corresponding data across distinct databases effortlessly.`,
  `Data management and auditing features in Excel provide robust mechanisms to maintain integrity across vast government datasets. The Sort and Filter commands allow ministerial staff to organize thousands of beneficiary records alphabetically, chronologically, or by district priority. Conditional Formatting visually highlights critical thresholds, such as budget expenditures exceeding sanctioned allocations or pending audit queries. In addition, Pivot Tables represent one of the most powerful data summarization tools in Excel, enabling clerks to aggregate, pivot, and analyze multi-column datasets with simple drag-and-drop actions, generating instant cross-tabulated reports without writing complex code.`,
  `Data security and accuracy safeguards are equally vital in administrative spreadsheet workflows. Clerks must know how to implement Data Validation rules to restrict user input—such as preventing negative budget entries or restricting date ranges—and protect sensitive workbooks using passwords to prevent unauthorized tampering. Visualizing complex fiscal trends through standard charts (bar charts, line graphs, and pie charts) enhances clarity in cabinet presentations and legislative committee reviews. Mastery of Microsoft Excel transforms raw administrative figures into actionable intelligence, empowering clerks to execute fiscal governance with speed, accuracy, and professional excellence.`,
  `Regular practice with keyboard shortcuts, such as navigation keys, auto-fill drag handles, and quick formula entry, drastically accelerates clerical workflow in high-volume administrative environments. Understanding cell referencing modes—including relative referencing (A1), absolute referencing ($A$1), and mixed referencing ($A1 or A$1)—is essential when copying complex financial formulas across large payroll or expenditure matrices. Advanced spreadsheet mastery remains a defining asset for ministerial professionals in modern digital governance.`
]);

console.log(`Generated ${lessons.length} lessons for Part 1.`);
lessons.forEach(l => console.log(`Lesson ${l.id}: ${l.words} words - ${l.title}`));

// Generate TypeScript code
const tsContent = `// Part 1: Lessons 1 to 20
export interface EnglishTestLesson {
  id: number;
  title: string;
  category: string;
  content: string;
}

export const PART1_LESSONS: EnglishTestLesson[] = ${JSON.stringify(lessons.map(l => ({
  id: l.id,
  title: l.title,
  category: l.category,
  content: l.content
})), null, 2)};
`;

fs.writeFileSync(path.join(__dirname, '../src/data/lessons/part1.ts'), tsContent, 'utf8');
console.log('Successfully wrote src/data/lessons/part1.ts!');
