const fs = require('fs');
const path = require('path');

// Helper to count words
function countWords(str) {
  return str.trim().split(/\s+/).filter(Boolean).length;
}

// We will define comprehensive content for all 100 lessons
// Each lesson will be enriched with multiple detailed paragraphs to ensure word count >= 700.

const lessonData = [
  {
    id: 1,
    title: 'Exercise : 1/100 - Rajasthan Geography & Physical Divisions',
    category: 'Rajasthan Geography',
    baseTopic: 'Rajasthan Geography and Physiographic Divisions',
    sections: [
      `Rajasthan is the largest state in the Republic of India in terms of total geographical area, covering approximately three hundred forty-two thousand two hundred thirty-nine square kilometres, which represents about 10.41 percent of the total landmass of India. Situated in the north-western region of the subcontinent, it shares international boundaries with Pakistan across five border districts in the west and northwest, while bordering the Indian states of Punjab, Haryana, Uttar Pradesh, Madhya Pradesh, and Gujarat. The tropic of cancer passes through the southernmost tip of the state, traversing the districts of Banswara and Dungarpur. The physical geography of Rajasthan presents a fascinating mosaic of extreme climatic variations, diverse geological formations, distinct soil profiles, and unique biological adaptations. Understanding these physical characteristics is essential for administrative personnel to plan regional developmental projects, water distribution networks, and disaster management strategies efficiently.`,
      `The state is broadly classified into four major physiographic divisions: the Western Sandy Plains or the Great Indian Thar Desert, the Aravalli Mountain Range, the Eastern Plains, and the South-Eastern Hadoti Plateau. The Western Sandy Plains encompass more than sixty percent of the state total land area and are home to nearly forty percent of its population. This arid tract is further subdivided into the Marusthali, characterized by shifting sand dunes known as Dhrians, and the semi-arid Rajasthan Bagar, which includes inland drainage basins such as the Shekhawati tract and the fertile Luni River basin. Despite severe climatic constraints, sparse rainfall, and extreme temperature fluctuations, the Thar Desert is considered one of the most densely populated desert ecosystems in the world, sustained by resilient pastoral communities, hardy desert livestock, and innovative traditional rainwater collection systems.`,
      `The Aravalli Mountain Range is one of the oldest fold mountain systems in the world, dating back to the Precambrian geological era. Running diagonally across Rajasthan from southwest near Mount Abu to northeast up to the Khetri belt and extending to the Raisina Hill in New Delhi, the Aravalli range spans approximately six hundred ninety-two kilometres, with five hundred fifty kilometres lying entirely within Rajasthan. Guru Shikhar, situated near Mount Abu in the Sirohi district, stands as the highest peak of the range with an elevation of one thousand seven hundred twenty-two metres above mean sea level. The Aravallis act as a crucial watershed and climatic divide, preventing the eastward expansion of the Thar Desert into the fertile agricultural plains of eastern Rajasthan and Madhya Pradesh, while also serving as the source for several major seasonal river systems including the Banas, Luni, Sabarmati, and Sukri.`,
      `The Eastern Plains of Rajasthan lie to the east of the central Aravalli hills, encompassing the fertile river basins of the Banas, Banganga, and the Middle Mahi river, also known as the Chappan Plain in the Banswara and Pratapgarh region. Formed primarily by extensive alluvial deposits brought down by perennial and seasonal river streams, these plains possess highly productive soils such as loamy sand and clayey loam, supporting intensive multi-crop agriculture including wheat, mustard, barley, and pulses. In contrast, the South-Eastern Hadoti Plateau, covering districts like Kota, Bundi, Baran, and Jhalawar, represents an extension of the Deccan Lava Trap, characterized by rich black cotton soil, undulating basaltic terrain, and significant limestone deposits. This region receives the highest average annual precipitation in the state and is extensively drained by the perennial Chambal river and its tributaries, making it a major powerhouse for agro-industries and thermal power generation.`,
      `For administrative officers and ministerial staff preparing for Rajasthan state examinations, mastering the detailed nuances of physical geography is vital. Land revenue administration, district boundary demarcations, crop insurance assessments, drought relief allocations, and watershed management all depend heavily on accurate geographical understanding. Clerks must accurately record local land classification terminology such as Chahi (irrigated land), Barani (unirrigated rainfed land), and Magra (rocky hill slopes) in village land revenue registers. Familiarity with topographical maps, district profiles, agro-climatic zones, and ground water vulnerability indexes ensures that clerical support in government secretariats and district collectorates contributes directly to sound policymaking, balanced regional development, and effective public grievance redressal across the state.`
    ]
  },
  {
    id: 2,
    title: 'Exercise : 2/100 - Historic Forts and World Heritage Sites',
    category: 'Art & Culture',
    baseTopic: 'Historic Forts, Architecture, and World Heritage Sites in Rajasthan',
    sections: [
      `The architectural brilliance, chivalric heritage, and heroic saga of Rajasthan are immortalized in its majestic hill forts, formidable citadel ramparts, and opulent royal palaces. In 2013, the World Heritage Committee of UNESCO officially designated six magnificent hill forts of Rajasthan as UNESCO World Heritage Sites, celebrating their outstanding universal value, strategic defensive engineering, and rich cultural syncretism. These six celebrated monuments include Chittorgarh Fort, Kumbhalgarh Fort in Rajsamand, Sawai Madhopur Ranthambore Fort, Jaisalmer Fort, Gagron Fort in Jhalawar, and Amber Fort in Jaipur. Spread across distinct geographical terrains ranging from dense forests and rugged Aravalli ridges to expansive desert sands and river confluences, these forts illustrate the pinnacle of Rajput defensive military architecture evolved over centuries between the eighth and nineteenth centuries.`,
      `Chittorgarh Fort, perched atop a steep five-hundred-foot-high rocky plateau, stands as an eternal monument to Rajput valour, patriotism, and the supreme sacrifice of Jauhar. Spanning over seven hundred acres, it is recognized as the largest fort complex in India and was the legendary capital of the Sisodia dynasty of Mewar. Within its massive stone ramparts lie historic landmarks such as the nine-storey Vijay Stambha or Tower of Victory erected by Maharana Kumbha to commemorate his victory over the armies of Malwa and Gujarat, the Kirti Stambha dedicated to Jain Tirthankara Adinatha, and the historic palaces of Maharana Ratan Singh and Rani Padmini. The fort endured three epic sieges by Alauddin Khalji, Bahadur Shah of Gujarat, and Mughal Emperor Akbar, each followed by heroic battles and tragic collective sacrifices that continue to inspire Rajasthani folk ballads and national historical memory.`,
      `Kumbhalgarh Fort, situated amidst the rugged ridges of the western Aravalli range in Rajsamand district, is renowned worldwide for possessing the second-longest continuous fortification wall on Earth, stretching over thirty-six kilometres and wide enough for multiple horsemen to ride abreast. Built during the fifteenth century by Maharana Kumbha under the architectural guidance of master builder Mandan, Kumbhalgarh was designed to be virtually impregnable, serving as a secure royal refuge during times of foreign invasion. It is celebrated as the birthplace of Maharana Pratap and contains over three hundred sixty ancient Hindu and Jain temples, alongside the Badal Mahal palace crowning the highest cliff. Further east, the Gagron Fort in Jhalawar represents an exceptional example of a Jal Durg or water fort, surrounded on three sides by the swirling waters of the Ahu and Kali Sindh rivers without needing an artificial moat.`,
      `In the arid western desert, Jaisalmer Fort, affectionately called Sonar Qila or the Golden Fort, rises like a golden mirage from the Trikuta Hill amidst shifting sands. Built in 1156 AD by Rawal Jaisal using indigenous yellow Jurassic sandstone, it is one of the very few living forts in the world, with nearly a fourth of the old city population residing within its triple-layered defensive walls. The fort houses exquisite Jain temples adorned with intricate Torana gateways and delicate filigree stone carvings, alongside the Raj Mahal palace and the invaluable manuscripts preserved in the Jinbhadra Suri Gyan Bhandar. In Jaipur, Amber Fort displays a splendid synthesis of Rajput and Mughal artistic traditions, featuring the world-famous Sheesh Mahal inlaid with Belgian convex mirrors, grand courtyards, and the sacred Shila Devi temple. Preserving these invaluable monuments fosters global tourism, generates sustainable local employment, and protects the living traditions of Rajasthan.`
    ]
  },
  {
    id: 3,
    title: 'Exercise : 3/100 - The Role of Lower Division Clerks in Administration',
    category: 'Office Procedures',
    baseTopic: 'Administrative Role and Responsibilities of Lower Division Clerks',
    sections: [
      `The Lower Division Clerk, commonly designated as LDC or Junior Assistant in government departments and subordinate offices of Rajasthan, forms the fundamental administrative backbone of public service delivery. The functioning of government secretariats, directorates, collectorates, municipal bodies, and public utility offices relies heavily on the efficiency, accuracy, and diligence of ministerial staff. The primary duties of an LDC encompass receiving and registering incoming postal and electronic correspondence (Dak), diarizing files, maintaining department subject registers, preparing standard office notes, cross-referencing statutory rules and historical precedents, and ensuring prompt dispatch of executive orders to subordinate field offices and concerned citizens.`,
      `With the comprehensive modernization of public administration through digital governance platforms, such as the integrated e-Office suite and RajKaj portal, the traditional role of ministerial clerks has evolved from physical paper filing to high-speed digital record management. Clerks are now required to possess exceptional bilingual typing speed and precision in both English and Hindi, along with working proficiency in word processing, electronic spreadsheets, database querying, and secure digital signature validation. Typing speed evaluation tests conducted by the Rajasthan Staff Selection Board (RSSB) are designed with rigorous standards to ensure that recruited personnel can draft official memorandums, generate statistical reports, and process citizen grievance files without introducing errors or administrative delays.`,
      `A crucial dimension of a clerk daily responsibility is the strict adherence to the Secretariat Manual of Office Procedure (SMOP) and the Rajasthan Service Rules (RSR). Every incoming file must follow an established movement register, with noting drafted on the left-hand side of the docket and correspondence placed on the right-hand side. Clerks must carefully analyze the legal, administrative, and financial implications of every case before placing it before Section Officers, Assistant Secretaries, or District Collectors. A well-trained clerk understands the distinction between Routine Notes, Detailed Notes, and Summary Proposals, ensuring that concise, factual, and unambiguous summaries are placed before executive decision-makers for timely sanctions and policy clearances.`,
      `In addition to general file management, clerks working in establishment, accounts, and legal branches handle critical tasks such as employee pay fixation, maintenance of service books, leave entitlement calculations, pension proposal drafting, and assembling replies for Right to Information (RTI) petitions and legislative assembly questions. Accuracy in numerical calculations, dates, and statutory citations is paramount; an oversight in record-keeping can result in legal disputes, audit objections, or denial of legitimate welfare benefits to citizens. Therefore, ministerial civil servants must uphold the highest standards of professional integrity, confidentiality, and citizen-centric responsiveness, ensuring that public administration in Rajasthan operates with exemplary transparency, promptness, and administrative fairness.`
    ]
  }
];

console.log('Building full generator...');
