const fs = require('fs');
const path = require('path');

function countWords(str) {
  return str.trim().split(/\s+/).filter(Boolean).length;
}

// Supplementary authentic, topic-specific paragraphs to bring each lesson to 720+ words
const expansionsPart1 = {
  5: [
    `In contemporary state administrative offices, understanding the role of secondary storage technologies and backup topologies is paramount. Solid State Drives (SSDs) utilizing NVMe (Non-Volatile Memory Express) protocols have largely superseded traditional spinning hard disks in government desktop workstations, reducing application load times from minutes to seconds. Clerks frequently manipulate large scanned gazettes, voter registries, and high-resolution cadastral maps where random read-write performance is critical. Regularly creating offsite encrypted backups on Network Attached Storage (NAS) or state cloud repositories protects critical citizen records against ransomware extortion and hardware wear.`,
    `Furthermore, input and output peripheral management requires ministerial clerks to master device configuration and driver updates. High-speed duplex network laser printers in government dispatch sections require appropriate toner yield monitoring, paper jam troubleshooting, and network IP port mapping. Document scanners equipped with Optical Character Recognition (OCR) software allow clerks to digitize legacy paper files into searchable PDF formats directly indexed into e-Office document management systems. Understanding hardware specifications enables junior administrative personnel to draft accurate technical requisitions for departmental computer hardware procurements, ensuring fiscal prudence and operational efficiency.`
  ],
  6: [
    `The integration of princely covenant agreements necessitated the creation of the Rajasthan Public Service Commission (RPSC) in Ajmer to conduct merit-based civil service recruitment, replacing hereditary court appointments with open competitive examinations. The unification also demanded the harmonization of distinct princely currencies, stamp duties, and weights and measures into standard national metrics. For administrative personnel, reviewing historical covenant files requires an understanding of how regional Jagir abolition laws, land tenancy acts, and privy purse abolitions reshaped agrarian ownership across Mewar, Marwar, and Dhundhar.`,
    `Today, the legacy of unification serves as a guiding light for administrative cohesion and statewide regional integration. Connecting isolated desert outposts, Aravalli tribal belts, and southeastern agricultural plains through modern expressways, state high-speed data networks (RajNET), and uniform administrative jurisdictions fulfills the vision of the state founding fathers. Ministerial staff uphold this unified constitutional framework daily by executing equal and impartial administrative service across every village and municipality.`
  ],
  7: [
    `The financial autonomy of Panchayati Raj Institutions has been significantly bolstered through the recommendations of the State Finance Commission (SFC) and the Central Finance Commission. Untied and tied developmental grants are directly credited to Gram Panchayat bank accounts via the Public Financial Management System (PFMS), eliminating bureaucratic delays and leakages. Village development plans are formulated through participatory 'Sabki Yojna Sabka Vikas' campaigns, where villagers prioritize community assets such as community water purification plants, Anganwadi buildings, solar street lighting, and village drainage systems.`,
    `Ministerial clerks in Panchayat Samitis assist Block Development Officers in auditing rural expenditure vouchers, reconciling bank passbooks, updating geo-tagged photos of completed rural assets on the Bhuvan Panchayat portal, and issuing caste and domicile verification reports. Robust local self-governance transforms remote rural hamlets into empowered, self-sustaining socio-economic hubs, ensuring that the fruits of national developmental progress reach the most vulnerable citizen at the grassroots.`
  ],
  8: [
    `Groundwater over-exploitation across critical and over-exploited blocks in Rajasthan poses a severe hydrological challenge. The Central Ground Water Board and State Ground Water Department implement artificial recharge projects, contour bunding, check dams, and percolation tanks under the Atal Bhujal Yojana. In arid western districts, rooftop rainwater harvesting structures (Tankas) and community ponds (Nadis) are scientifically integrated with local storm water drainage channels to capture seasonal precipitation before it evaporates under scorching temperatures.`,
    `Water resource department clerks maintain meticulous dam gauge registers, discharge logs during monsoon gates opening, and water tariff assessment records for industrial and irrigation consumers. Familiarity with inter-state agreements regarding the Ravi-Beas, Yamuna, and Narmada river waters ensures accurate record-keeping during inter-state tribunal hearings. Safeguarding Rajasthan surface and subterranean water reserves remains an indispensable priority for public welfare, agricultural stability, and economic growth.`
  ],
  9: [
    `The rich oral storytelling traditions of Rajasthan are inextricably linked with theatrical folk dance forms such as Khyal, Tamasha, and Bhavai. The Bhavai dance of Mewar is an exhilarating demonstration of balance and courage, where female dancers balance up to eight or nine earthen pots or brass pitchers on their heads while pivoting upon the edge of a sword, broken glass shards, or the rim of a brass thali. In the Shekhawati region, the Dhamal and Chang dances performed during the festive spring festival of Holi reflect spontaneous rustic joy, accompanied by witty topical satire mocking social foibles.`,
    `Preserving these invaluable artistic traditions in an era of rapid urbanization and digital entertainment is an important mandate of the state Department of Art and Culture. The government provides performance grants, pension support to indigent folk artists, and opportunities to perform in national and international cultural exchange festivals. Lower Division Clerks in cultural academies manage artist empanelment registers, process performance honorariums, and maintain digital archives of traditional musical ballads, ensuring that Rajasthan artistic soul continues to shine brilliantly across the globe.`
  ],
  10: [
    `The integration of artificial intelligence and automated analytics into Rajasthan e-governance infrastructure has dramatically accelerated public file processing and citizen grievance resolution. The Rajasthan Sampark citizen helpline (Toll-Free 181) registers grievances across diverse departments, utilizing automated call routing, SMS tracking, and automated escalation to higher authorities if a complaint remains unresolved beyond stipulated timelines. District Collectors conduct weekly video-conferencing review sessions with Sub-Divisional Magistrates and Tehsildars to analyze pendency rates on digital dashboards.`,
    `For ministerial staff and LDCs, proficiency in digital office tools is no longer optional; it is the core criterion of administrative performance. Clerks must verify digital certificates, process pension life certificates using Aadhaar-enabled biometric facial recognition, and reconcile electronic treasury scrolls on the Integrated Financial Management System (IFMS). By removing physical barriers between citizens and state administrative machinery, Rajasthan e-governance initiatives embody the democratic ideal of transparent, participatory, and efficient public administration.`,
    `Furthermore, the expansion of the RajNET optical fiber and satellite network to all Gram Panchayats ensures that even the most remote desert and tribal settlements remain plugged into real-time government service streams. Ministerial employees must maintain meticulous data logs, safeguard sensitive citizen databases under national cyber security guidelines, and uphold the public right to timely, corruption-free public services across all administrative touchpoints.`
  ],
  11: [
    `Modern operating systems also incorporate sophisticated multitasking and multithreading capabilities that allow clerical staff to juggle heavy workloads without systemic lockups. A clerk can simultaneously compose an official cabinet memorandum in a word processor, run database queries on land revenue records, stream a departmental video conference, and calculate budget figures in a spreadsheet. The operating system virtual memory manager dynamically swaps memory pages between RAM and storage drives, preventing system crashes during intensive operations.`,
    `File access permissions and security privileges are strictly enforced by the operating system security subsystem. In administrative setups, User Account Control (UAC) and Group Policy Objects (GPO) restrict standard clerical workstations from installing unauthorized third-party software, altering core registry configurations, or executing unverified scripts. Understanding file permissions—such as Read, Write, and Execute—ensures that sensitive departmental files stored on shared local network drives are accessible only to authorized personnel, preventing data leakage and ensuring administrative integrity.`
  ],
  12: [
    `In addition to utility-scale solar parks, the wind energy sector in Rajasthan has expanded rapidly along the windy ridges of Jaisalmer, Barmer, and Pratapgarh. Hybrid renewable projects combining solar photovoltaic panels and wind turbines on the same land parcel optimize transmission line infrastructure and provide more consistent 24/7 power output. The state policy framework incentivizes green energy corridors, establishing high-capacity substations and transmission lines that transport clean power directly from remote desert dunes to major national industrial load centers.`,
    `Clerical personnel in the Energy Department, Rajasthan Rajya Vidyut Prasaran Nigam Limited (RVPN), and DISCOMs handle extensive administrative files regarding renewable energy purchase obligations (RPO), net-metering solar rooftop applications, and power purchase billing reconciliations. Mastery of energy accounting terminology, regulatory commission tariff orders, and green power subsidy documentation ensures smooth execution of state clean energy mandates. Rajasthan solar and wind revolution exemplifies how visionary public policy can turn geographic adversity into sustainable economic leadership.`
  ],
  13: [
    `Environmental sustainability and scientific reclamation in the mining industry are enforced through strict statutory frameworks, including mandatory Environmental Clearances (EC) from the Ministry of Environment, Forest and Climate Change (MoEFCC) and Consent to Operate from the Rajasthan State Pollution Control Board (RSPCB). Mining leaseholders must execute progressive mine closure plans, establish green afforestation belts around lease perimeters, and employ dust-suppression water sprinklers along haulage roads. The state Department of Mines conducts routine drone-based volumetric surveys to detect illegal boundary encroachments and over-excavation.`,
    `Ministerial clerks in mining collectorates and directorates manage complex documentation involving mineral transit passes (e-Ravanna), lease transfer applications, earnest money deposit (EMD) reconciliations, and royalty recovery notices. Clerks must cross-reference geological survey maps, check boundary coordinates against prohibited forest land databases, and maintain accurate ledger entries for royalty payments. Diligent clerical administration safeguards state mining revenue while supporting sustainable industrial growth and community welfare through the District Mineral Foundation Trust.`
  ],
  14: [
    `The role of pioneering regional newspapers and political publications in awakening nationalist sentiment cannot be overstated. Publications such as 'Rajasthan Kesari', 'Naveen Rajasthan', and 'Tarun Rajasthan' published under the editorial stewardship of Vijay Singh Pathik and Ramnarayan Choudhary boldly exposed the atrocities of feudal Jagirdars and the indifference of British political agents. Despite frequent censorship, police raids, and printing press confiscations, these underground publications circulated widely among literate peasants, village teachers, and youth, building an unshakeable resolve for democratic freedom.`,
    `The integration of tribal freedom fighters into the anti-colonial resistance also forms a glorious chapter of Rajasthan history. Under the spiritual and social leadership of Govind Guru, the Bhil tribes organized the historic Bhagat Movement, culminating in the tragic Mangarh Hill massacre of November 17, 1913, where over fifteen hundred unarmed Bhil tribal patriots were mercilessly martyred by British troops and princely state forces. Remembering and honoring these profound sacrifices is an essential duty of every public servant, reinforcing pride in our constitutional democracy.`
  ],
  15: [
    `Advanced table formatting and cross-referencing capabilities in Microsoft Word are essential for preparing comprehensive administrative reports, legislative assembly answers, and employee seniority lists. Clerks must master creating structured multi-column tables, merging and splitting cells, applying subtle shading to header rows, and configuring repeating header rows so that large tabular statements remain clear across multi-page printouts. Utilizing custom Tab stops with dot leaders allows staff to produce perfectly aligned tables of contents and financial summary sheets without irregular spacing.`,
    `Document security and final publication formatting are equally critical. Before releasing official notifications or executive orders, clerks must remove hidden metadata and revision histories using the Document Inspector, apply digital watermarks such as 'CONFIDENTIAL' or 'DRAFT', and convert documents into standardized PDF/A format for long-term legal archiving. Mastering keyboard shortcuts—such as Ctrl+C for copy, Ctrl+V for paste, Ctrl+Z for undo, Ctrl+F for search, and Ctrl+H for replace—drastically boosts typing speed and clerical productivity during high-pressure legislative sessions.`
  ],
  16: [
    `The conservation of wetland ecosystems and aquatic avifauna in Rajasthan represents an essential component of ecological governance. The Sambhar Salt Lake, recognized as a Ramsar site of international significance, serves as a crucial wintering habitat for tens of thousands of migratory lesser and greater flamingos arriving from Central Asia and Africa. Monitoring avian health, regulating industrial effluent discharges, and protecting saline wetlands against unauthorized salt pans are major priorities coordinated between the Forest Department, Revenue authorities, and the Sambhar Salts Limited administration.`,
    `Ministerial staff in divisional forest offices and wildlife sanctuaries handle sensitive conservation dockets, including processing tranquilizer drug permits for veterinarian rescue teams, managing eco-development committee (EDC) village funds, maintaining wildlife mortality post-mortem records, and disbursing ex-gratia compensation to families affected by wildlife human conflicts. Diligent documentation and transparent record-keeping support forest rangers and wildlife wardens in preserving the rich biological heritage of Rajasthan for generations to come.`
  ],
  17: [
    `Modern agricultural transformation in Rajasthan emphasizes value addition, agro-processing clusters, and the expansion of the 'One District One Product' (ODOP) initiative. High-value crops such as organic cumin from Jalore, coriander from Kota, kinnow citrus from Sri Ganganagar, and garlic from Baran are processed and packaged in state-of-the-art agro-food parks established by the Rajasthan State Industrial Development and Investment Corporation (RIICO). Developing cold chain logistics and farm-gate warehouses reduces post-harvest losses and enables farmers to realize premium export prices.`,
    `Clerical personnel in the Agriculture and Horticulture Departments process capital subsidy claims for solar-powered micro-irrigation systems, verify farmer registration details on the RajKisan Saathi portal, and audit cooperative credit society disbursement scrolls. Familiarity with seasonal crop damage reporting schedules (Girdawari) and insurance claim settlement rules under the Pradhan Mantri Fasal Bima Yojana allows clerks to assist distressed agricultural families efficiently, making public administration an active partner in rural agrarian prosperity.`
  ],
  18: [
    `The commercial, economic, and tourism impact of Rajasthan fairs and festivals is enormous. These cultural congregations provide an essential livelihood platform for rural artisans, potters, weavers, camel breeders, and traditional sweetmakers who sell their handcrafted goods to visitors from across the country. In desert districts like Jaisalmer and Bikaner, international tourist footfall peaks during winter cultural festivals, filling heritage hotels, desert camps, and local handicrafts emporiums, generating valuable foreign exchange and uplifting the service economy.`,
    `Administrative clerks in municipal councils, tourism reception centers, and district collectorates manage complex logistical files ahead of major festivals. Tasks include issuing fairground vendor licenses, coordinating stage production contracts for cultural nights, processing temporary public transport permits with the state road transport corporation, and auditing tourist facilitation budgets. Seamless clerical coordination ensures that these colorful celebrations maintain flawless public safety, cleanliness, and security while showcasing the hospitality and royal grandeur of Rajasthan.`
  ],
  19: [
    `A vital duty of ministerial clerks in office procedure is the accurate preparation of the Reference Slip, Flagging, and Urgency Grading on official files. When placing a file before senior officers, clerks must affix distinct visual priority tags such as 'IMMEDIATE', 'PRIORITY', or 'ASSEMBLY QUESTION' to ensure that time-sensitive public matters receive expedited attention. Historical files and relevant statutory acts must be tagged with alphabetized flags (Flag 'A', Flag 'B') and cited precisely in the margin of the note, enabling the decision-maker to cross-check legal precedents in seconds without flipping through hundreds of paper sheets.`,
    `In the digital era of the RajKaj portal, electronic file tracking systems (e-File) have automated docket generation and movement registers. However, the clerk intellectual responsibility to scrutinize rule provisions, detect conflicting departmental guidelines, and craft concise, objective draft orders remains indispensable. A well-organized, grammatically precise, and audit-compliant file note is a shield that protects the executive from administrative mistakes and ensures that public policies are implemented with speed, integrity, and absolute fidelity to the law.`
  ],
  20: [
    `Data visualization through dynamic Excel charts—such as clustered column charts, trend lines, and donut graphs—is essential for presenting complex financial and operational performance data to department secretaries and cabinet sub-committees. Clerks can transform lengthy rows of budget expenditure figures into compelling visual dashboards that instantly communicate progress against targets, highlighting fiscal deficits or administrative delays. Utilizing the Goal Seek and Scenario Manager tools enables budget analysts to model revenue projections under varying tax recovery assumptions.`,
    `Clerical staff must also master Excel data protection and sharing controls. Password-protecting sensitive salary sheets, locking formula cells to prevent accidental overwriting, and removing personal identification data before sharing public statistical digests ensures data privacy and regulatory compliance. Incorporating standard keyboard shortcuts—such as F4 for repeating actions or toggling absolute references, Ctrl+Shift+L for toggling filters, and Alt+= for auto-summing—empowers clerks to process voluminous datasets with unmatched speed, accuracy, and professional confidence.`
  ]
};

console.log('Expansion helper loaded for Part 1.');
module.exports = { expansionsPart1, countWords };
