const fs = require('fs');
const path = require('path');

function countWords(str) {
  return str.trim().split(/\s+/).filter(Boolean).length;
}

const lessons = [];

function addLesson(id, title, category, paras) {
  const content = paras.map(p => p.trim()).filter(Boolean).join('\n\n');
  const w = countWords(content);
  if (w < 700) {
    throw new Error(`Part 1 - Lesson ${id} (${title}) has only ${w} words (<700)!`);
  }
  lessons.push({ id, title, category, content, words: w });
}

// 1. Rajasthan Geography & Physical Divisions
addLesson(1, "Exercise : 1/100 - Rajasthan Geography & Physical Divisions", "Rajasthan Geography", [
  "Rajasthan is the largest state in the Republic of India in terms of total geographical area, covering approximately three hundred forty-two thousand two hundred thirty-nine square kilometres, which represents about 10.41 percent of the total landmass of India. Situated in the north-western region of the subcontinent, it shares international boundaries with Pakistan across five border districts in the west and northwest, while bordering the Indian states of Punjab, Haryana, Uttar Pradesh, Madhya Pradesh, and Gujarat. The tropic of cancer passes through the southernmost tip of the state, traversing the districts of Banswara and Dungarpur. The physical geography of Rajasthan presents a fascinating mosaic of extreme climatic variations, diverse geological formations, distinct soil profiles, and unique biological adaptations. Understanding these physical characteristics is essential for administrative personnel to plan regional developmental projects, water distribution networks, and disaster management strategies efficiently.",
  "The state is broadly classified into four major physiographic divisions: the Western Sandy Plains or the Great Indian Thar Desert, the Aravalli Mountain Range, the Eastern Plains, and the South-Eastern Hadoti Plateau. The Western Sandy Plains encompass more than sixty percent of the state total land area and are home to nearly forty percent of its population. This arid tract is further subdivided into the Marusthali, characterized by shifting sand dunes known as Dhrians, and the semi-arid Rajasthan Bagar, which includes inland drainage basins such as the Shekhawati tract and the fertile Luni River basin. Despite severe climatic constraints, sparse rainfall, and extreme temperature fluctuations, the Thar Desert is considered one of the most densely populated desert ecosystems in the world, sustained by resilient pastoral communities, hardy desert livestock, and innovative traditional rainwater collection systems.",
  "The Aravalli Mountain Range is one of the oldest fold mountain systems in the world, dating back to the Precambrian geological era. Running diagonally across Rajasthan from southwest near Mount Abu to northeast up to the Khetri belt and extending to the Raisina Hill in New Delhi, the Aravalli range spans approximately six hundred ninety-two kilometres, with five hundred fifty kilometres lying entirely within Rajasthan. Guru Shikhar, situated near Mount Abu in the Sirohi district, stands as the highest peak of the range with an elevation of one thousand seven hundred twenty-two metres above mean sea level. The Aravallis act as a crucial watershed and climatic divide, preventing the eastward expansion of the Thar Desert into the fertile agricultural plains of eastern Rajasthan and Madhya Pradesh, while also serving as the source for several major seasonal river systems including the Banas, Luni, Sabarmati, and Sukri.",
  "The Eastern Plains of Rajasthan lie to the east of the central Aravalli hills, encompassing the fertile river basins of the Banas, Banganga, and the Middle Mahi river, also known as the Chappan Plain in the Banswara and Pratapgarh region. Formed primarily by extensive alluvial deposits brought down by perennial and seasonal river streams, these plains possess highly productive soils such as loamy sand and clayey loam, supporting intensive multi-crop agriculture including wheat, mustard, barley, and pulses. In contrast, the South-Eastern Hadoti Plateau, covering districts like Kota, Bundi, Baran, and Jhalawar, represents an extension of the Deccan Lava Trap, characterized by rich black cotton soil, undulating basaltic terrain, and significant limestone deposits. This region receives the highest average annual precipitation in the state and is extensively drained by the perennial Chambal river and its tributaries, making it a major powerhouse for agro-industries and thermal power generation.",
  "For administrative officers and ministerial staff preparing for Rajasthan state examinations, mastering the detailed nuances of physical geography is vital. Land revenue administration, district boundary demarcations, crop insurance assessments, drought relief allocations, and watershed management all depend heavily on accurate geographical understanding. Clerks must accurately record local land classification terminology such as Chahi (irrigated land), Barani (unirrigated rainfed land), and Magra (rocky hill slopes) in village land revenue registers. Familiarity with topographical maps, district profiles, agro-climatic zones, and ground water vulnerability indexes ensures that clerical support in government secretariats and district collectorates contributes directly to sound policymaking, balanced regional development, and effective public grievance redressal across the state.",
  "Furthermore, the ongoing administrative restructuring and formation of new districts in Rajasthan highlights the necessity of geographic literacy in governance. Realigned boundaries require revenue personnel to re-catalogue land parcels, adjust catchment areas, recalibrate sub-divisional jurisdictions, and update GIS mapping layers on the state Bhunaksha digital land portal. Field functionaries must evaluate regional micro-climates, soil fertility indices, and mineral belts when recommending industrial park allocations or municipal extensions. Mastery over geographical facts is therefore not merely an academic exercise for competitive examinations, but a practical requirement for ensuring equitable public administration and sustainable resource utilization across every corner of the state."
]);

// 2. Historic Forts and World Heritage Sites
addLesson(2, "Exercise : 2/100 - Historic Forts and World Heritage Sites", "Art & Culture", [
  "The architectural brilliance, chivalric heritage, and heroic saga of Rajasthan are immortalized in its majestic hill forts, formidable citadel ramparts, and opulent royal palaces. In 2013, the World Heritage Committee of UNESCO officially designated six magnificent hill forts of Rajasthan as UNESCO World Heritage Sites, celebrating their outstanding universal value, strategic defensive engineering, and rich cultural syncretism. These six celebrated monuments include Chittorgarh Fort, Kumbhalgarh Fort in Rajsamand, Sawai Madhopur Ranthambore Fort, Jaisalmer Fort, Gagron Fort in Jhalawar, and Amber Fort in Jaipur. Spread across distinct geographical terrains ranging from dense forests and rugged Aravalli ridges to expansive desert sands and river confluences, these forts illustrate the pinnacle of Rajput defensive military architecture evolved over centuries between the eighth and nineteenth centuries.",
  "Chittorgarh Fort, perched atop a steep five-hundred-foot-high rocky plateau, stands as an eternal monument to Rajput valour, patriotism, and the supreme sacrifice of Jauhar. Spanning over seven hundred acres, it is recognized as the largest fort complex in India and was the legendary capital of the Sisodia dynasty of Mewar. Within its massive stone ramparts lie historic landmarks such as the nine-storey Vijay Stambha or Tower of Victory erected by Maharana Kumbha to commemorate his victory over the armies of Malwa and Gujarat, the Kirti Stambha dedicated to Jain Tirthankara Adinatha, and the historic palaces of Maharana Ratan Singh and Rani Padmini. The fort endured three epic sieges by Alauddin Khalji, Bahadur Shah of Gujarat, and Mughal Emperor Akbar, each followed by heroic battles and tragic collective sacrifices that continue to inspire Rajasthani folk ballads and national historical memory.",
  "Kumbhalgarh Fort, situated amidst the rugged ridges of the western Aravalli range in Rajsamand district, is renowned worldwide for possessing the second-longest continuous fortification wall on Earth, stretching over thirty-six kilometres and wide enough for multiple horsemen to ride abreast. Built during the fifteenth century by Maharana Kumbha under the architectural guidance of master builder Mandan, Kumbhalgarh was designed to be virtually impregnable, serving as a secure royal refuge during times of foreign invasion. It is celebrated as the birthplace of Maharana Pratap and contains over three hundred sixty ancient Hindu and Jain temples, alongside the Badal Mahal palace crowning the highest cliff. Further east, the Gagron Fort in Jhalawar represents an exceptional example of a Jal Durg or water fort, surrounded on three sides by the swirling waters of the Ahu and Kali Sindh rivers without needing an artificial moat.",
  "In the arid western desert, Jaisalmer Fort, affectionately called Sonar Qila or the Golden Fort, rises like a golden mirage from the Trikuta Hill amidst shifting sands. Built in 1156 AD by Rawal Jaisal using indigenous yellow Jurassic sandstone, it is one of the very few living forts in the world, with nearly a fourth of the old city population residing within its triple-layered defensive walls. The fort houses exquisite Jain temples adorned with intricate Torana gateways and delicate filigree stone carvings, alongside the Raj Mahal palace and the invaluable manuscripts preserved in the Jinbhadra Suri Gyan Bhandar. In Jaipur, Amber Fort displays a splendid synthesis of Rajput and Mughal artistic traditions, featuring the world-famous Sheesh Mahal inlaid with Belgian convex mirrors, grand courtyards, and the sacred Shila Devi temple. Preserving these invaluable monuments fosters global tourism, generates sustainable local employment, and protects the living traditions of Rajasthan.",
  "From an administrative and conservation perspective, managing these world heritage properties involves coordinated efforts between the Archaeological Survey of India (ASI), the State Department of Archaeology and Museums, and local municipal corporations. Clerks and administrative officers handle budgeting for archaeological restorations, tourist facilitation facilities, encroachment monitoring, light and sound show operations, and international cultural exchange protocols. Rigorous documentation, record upkeep, and transparent management ensure that the architectural glory and cultural dignity of Rajasthan historic fortresses continue to inspire generations of domestic and international visitors.",
  "Preserving the physical integrity of these historic monuments in the twenty-first century demands modern conservation protocols, including structural stone consolidation, eco-sensitive buffer zone enforcement, sustainable tourist carrying-capacity modeling, and community engagement. Ministerial officers in the Department of Tourism and Culture draft annual monument maintenance budgets, process archaeological clearance dossiers for infrastructure projects, and coordinate tourist safety measures with heritage police battalions. The enduring majesty of Rajasthan hill forts serves as a living testament to the engineering genius, spiritual devotion, and immortal heroism of its builders, continuing to captivate historians and travelers worldwide."
]);

// 3. The Role of Lower Division Clerks in Administration
addLesson(3, "Exercise : 3/100 - The Role of Lower Division Clerks in Administration", "Office Procedures", [
  "The Lower Division Clerk, commonly designated as LDC or Junior Assistant in government departments and subordinate offices of Rajasthan, forms the fundamental administrative backbone of public service delivery. The functioning of government secretariats, directorates, collectorates, municipal bodies, and public utility offices relies heavily on the efficiency, accuracy, and diligence of ministerial staff. The primary duties of an LDC encompass receiving and registering incoming postal and electronic correspondence (Dak), diarizing files, maintaining department subject registers, preparing standard office notes, cross-referencing statutory rules and historical precedents, and ensuring prompt dispatch of executive orders to subordinate field offices and concerned citizens.",
  "With the comprehensive modernization of public administration through digital governance platforms, such as the integrated e-Office suite and RajKaj portal, the traditional role of ministerial clerks has evolved from physical paper filing to high-speed digital record management. Clerks are now required to possess exceptional bilingual typing speed and precision in both English and Hindi, along with working proficiency in word processing, electronic spreadsheets, database querying, and secure digital signature validation. Typing speed evaluation tests conducted by the Rajasthan Staff Selection Board (RSSB) are designed with rigorous standards to ensure that recruited personnel can draft official memorandums, generate statistical reports, and process citizen grievance files without introducing errors or administrative delays.",
  "A crucial dimension of a clerk daily responsibility is the strict adherence to the Secretariat Manual of Office Procedure (SMOP) and the Rajasthan Service Rules (RSR). Every incoming file must follow an established movement register, with noting drafted on the left-hand side of the docket and correspondence placed on the right-hand side. Clerks must carefully analyze the legal, administrative, and financial implications of every case before placing it before Section Officers, Assistant Secretaries, or District Collectors. A well-trained clerk understands the distinction between Routine Notes, Detailed Notes, and Summary Proposals, ensuring that concise, factual, and unambiguous summaries are placed before executive decision-makers for timely sanctions and policy clearances.",
  "In addition to general file management, clerks working in establishment, accounts, and legal branches handle critical tasks such as employee pay fixation, maintenance of service books, leave entitlement calculations, pension proposal drafting, and assembling replies for Right to Information (RTI) petitions and legislative assembly questions. Accuracy in numerical calculations, dates, and statutory citations is paramount; an oversight in record-keeping can result in legal disputes, audit objections, or denial of legitimate welfare benefits to citizens. Therefore, ministerial civil servants must uphold the highest standards of professional integrity, confidentiality, and citizen-centric responsiveness, ensuring that public administration in Rajasthan operates with exemplary transparency, promptness, and administrative fairness.",
  "Continuous professional skill enhancement and technological adaptability are vital for career progression from Junior Assistant to Senior Assistant, Assistant Section Officer, and Section Officer. As government departments transition towards artificial intelligence-driven document summarization, automated grievance categorization, and paperless workflows, clerks who maintain exceptional typing fluency, meticulous attention to detail, and a deep understanding of administrative jurisprudence will remain indispensable contributors to effective governance and citizen satisfaction in Rajasthan.",
  "Furthermore, ministerial personnel act as the primary interface between the citizen and the state machinery during public hearing days, Jan Sunwai camps, and revenue lok adalats. Recording citizen petitions accurately, tagging them with appropriate departmental subject codes, issuing instant acknowledgement receipts, and following up on pending compliance reports requires strong empathetic communication skills alongside clerical competence. A punctual, dedicated, and computer-literate Lower Division Clerk accelerates the entire administrative apparatus, transforming bureaucratic paperwork into rapid, tangible public service outcomes for millions of citizens.",
  "Ethical conduct and data security form additional pillars of ministerial responsibility. Clerical staff handle confidential government records, public procurement bids, and citizen personal data protected under statutory privacy norms. Adhering strictly to the Rajasthan Civil Services Conduct Rules, preventing unauthorized file disclosures, and maintaining clean, audit-compliant physical and digital file archives reinforces public trust in democratic institutions and administrative governance. Ministerial employees must continually refine their drafting competencies to reflect executive decisions with legal precision.",
  "Finally, time management and prioritized file disposal schedules dictate clerical efficiency during peak administrative periods such as legislative assembly sessions and annual budget formulations. Tracking urgent assembly questions, compiling starred question background dossiers under strict deadlines, and coordinating with subordinate field directorates requires tireless dedication. Clerks who master these multifaceted administrative responsibilities serve as the true bedrock of effective democratic governance across Rajasthan."
]);

// 4. Indira Gandhi Canal Project (IGNP)
addLesson(4, "Exercise : 4/100 - Indira Gandhi Canal Project (IGNP)", "Water Resources & Irrigation", [
  "Originating from the Harike Barrage in Punjab at the confluence of the Satluj and Beas rivers, the Indira Gandhi Canal Project (IGNP) is one of the most gigantic and ambitious irrigation canal networks in human history. Conceived by visionary engineer Kanwar Sain in 1948 to transform the arid wilderness of north-western Rajasthan into a productive green belt, the project was officially launched in 1958. It stretches across hundreds of kilometres through the states of Punjab, Haryana, and Rajasthan, terminating in the desert expanses of Jaisalmer and Barmer. The main canal, known as the Rajasthan Feeder and Rajasthan Main Canal, spans over six hundred forty-nine kilometres, accompanied by an extensive network of distribution channels, branches, and lift canals exceeding nine thousand kilometres in total length.",
  "The command area of the Indira Gandhi Canal is administratively categorized into Stage One and Stage Two. Stage One covers the northern districts of Sri Ganganagar, Hanumangarh, and parts of Bikaner, utilizing flow irrigation across relatively flatter plains. Stage Two extends into the more challenging desert terrain of Bikaner, Jaisalmer, Jodhpur, Nagaur, and Barmer, where water must be mechanically lifted using lift canals such as the Kanwar Sain Lift Canal, Gandheli Sahawa Lift Canal, Gajner Lift Canal, Kolayat Lift Canal, Phalodi Lift Canal, and Pokhran Lift Canal. The introduction of perennial canal water has triggered an unprecedented socioeconomic transformation, facilitating drinking water supply for millions of desert residents, supporting livestock herds, and enabling the commercial cultivation of cash crops including cotton, wheat, mustard, guar, groundnut, and kinnow citrus orchards.",
  "Despite its monumental developmental benefits, the Indira Gandhi Canal Project presents substantial environmental and ecological challenges that require continuous engineering oversight and administrative interventions. Uncontrolled flood irrigation across porous sandy soils underlain by impervious gypsum layers has led to severe waterlogging, soil salinization, and rising groundwater tables in low-lying depressions of Rawatsar and Hanumangarh. Furthermore, intensive silt deposition along unlined channels and weed infestation reduce canal flow velocity, requiring regular desiltation campaigns and modern canal lining works. The state command area development authority (CADA) actively promotes sprinkler irrigation systems, pressurized pipe distribution networks, and community water user associations (WUA) to maximize water use efficiency.",
  "For administrative clerks and revenue officials in canal command districts, managing canal-related files demands familiarity with technical terminology such as Chak (irrigation unit), Warabandi (rotational water distribution timetable), Mogha (canal water outlet), and Murabba (standard land division square). Revenue records must reflect precise water shares, crop loss assessments during seasonal canal closures, and distribution of subsidized sprinkler equipment. As climate variability and inter-state river water sharing treaties evolve, the optimal operation of the Indira Gandhi Canal remains central to the agricultural prosperity, food security, and ecological balance of western Rajasthan.",
  "The ongoing modernization of the canal network incorporates supervisory control and data acquisition (SCADA) systems, automated flow gates, and drone surveillance to detect breaches and illegal water siphoning. Sustainable desert agriculture under the IGNP represents a global benchmark for converting inhospitable arid landscapes into thriving agricultural hubs through engineering excellence, sound governance, and community resilience.",
  "Additionally, canal command development has fostered the growth of agro-processing industrial corridors, mandis, and warehousing hubs across Ganganagar, Bikaner, and Hanumangarh. Transporting agricultural produce from desert farm gates to national consumer markets has boosted per capita district incomes. Ensuring equitable water distribution at the tail-ends of distributaries remains a high administrative priority, demanding daily monitoring by irrigation executive engineers, revenue tehsildars, and ministerial desk officers.",
  "Afforestation belts planted along canal banks, known as shelterbelts, stabilize shifting sand dunes and prevent sand accumulation in water channels. These canal-side plantations of Dalbergia sissoo (Shisham), Acacia tortilis, and Tecomella undulata (Rohida) enhance local micro-climates, support biodiversity, and supply valuable timber, exemplifying an integrated approach to desert ecosystem management. Sustaining this hydrological marvel requires continuous investment in lining, desiltation, and community participatory water governance.",
  "Moreover, the canal plays an indispensable strategic role along India western international frontier, supplying clean drinking water to remote Border Security Force (BSF) outposts and border villages. The economic and strategic security conferred by the IGNP has converted previously inhospitable desert stretches into vibrant, self-reliant agrarian communities contributing significantly to national food reserves."
]);

// 5. Computer Fundamentals and Hardware Architecture
addLesson(5, "Exercise : 5/100 - Computer Fundamentals and Hardware Architecture", "Computer Fundamentals", [
  "A modern electronic digital computer is an advanced system designed to accept raw data as input, process it through a sequence of logical and arithmetical instructions, store intermediate and permanent records, and generate meaningful output for users. In modern public administration, computers have completely replaced traditional manual ledger systems, forming the core infrastructure for e-governance, digital treasury management, and citizen database maintenance. A comprehensive understanding of computer architecture, internal hardware components, peripheral devices, and system software is essential for clerical candidates seeking employment in government secretariats and public sector undertakings.",
  "The Central Processing Unit, commonly known as the CPU, acts as the primary computational engine and brain of the computer system. It consists of three fundamental structural modules: the Arithmetic Logic Unit (ALU), which performs all mathematical calculations and relational logical comparisons; the Control Unit (CU), which orchestrates the fetch, decode, and execute cycle across all connected subsystems; and internal high-speed register arrays that provide temporary storage for active data operands. Modern CPUs utilize multi-core architectures, enabling parallel execution of multiple software threads, which drastically speeds up document processing, statistical indexing, and encrypted data transmission.",
  "System memory is hierarchically structured to balance operational speed, data persistence, and cost. Primary storage consists of Random Access Memory (RAM), which is volatile and holds currently active programs and operating system routines, and Read Only Memory (ROM), which permanently stores firmware instructions such as the Basic Input Output System (BIOS) or Unified Extensible Firmware Interface (UEFI) required to bootstrap the machine. Cache memory, situated directly on or adjacent to the processor die, provides lightning-fast access to frequently referenced instructions. Secondary storage encompasses non-volatile storage mediums including Solid State Drives (SSD), Hard Disk Drives (HDD), and external optical or magnetic storage media, providing secure long-term repository for administrative databases.",
  "Input devices allow clerical operators to feed alphanumeric text and commands into the computer. Standard input peripherals include mechanical and membrane keyboards, optical mice, document scanners, biometric fingerprint readers, and Optical Mark Recognition (OMR) scanners used in public examinations. Output peripherals translate processed digital signals into human-readable formats, comprising High Definition visual display monitors, laser printers for generating official gazette notifications, dot matrix printers for multi-copy receipts, and high-speed network plotters for engineering blueprints. Connecting these peripherals requires standard high-speed bus interfaces such as Universal Serial Bus (USB), HDMI, DisplayPort, and PCIe expansion slots.",
  "Clerical officers must be equipped with practical hardware troubleshooting capabilities, including verifying device driver installations in the Device Manager, diagnosing memory bottlenecks using the Task Manager, configuring network printers, and ensuring proper power backup through Uninterruptible Power Supply (UPS) units. Maintaining hardware security, preventing unauthorized access through USB port blocking protocols, and executing periodic system backups protect sensitive governmental records from hardware failures and unauthorized tampering.",
  "Furthermore, understanding system bus topologies—including the control bus, data bus, and address bus—provides insight into data throughput bottlenecks. Knowledge of motherboard chipsets, thermal dissipation mechanisms such as heat sinks and cooling fans, and surge suppression safeguards hardware longevity in government office environments. Clerks who can quickly identify whether a malfunction stems from a loose SATA cable, faulty RAM seating, or a corrupted display adapter save valuable working hours and sustain uninterrupted public service workflows.",
  "Regular preventative hardware maintenance, such as dust cleaning of CPU ventilation grilles, testing uninterruptible power supply (UPS) batteries, and verifying disk health using SMART diagnostics, prevents sudden hardware breakdowns. As public administration increasingly relies on 24/7 digital public service portals, hardware reliability and prompt desktop troubleshooting are critical for maintaining administrative productivity. Mastery over foundational computer hardware architectures ensures seamless transition to advanced digital administrative workflows."
]);

// 6. Unification and Integration of Rajasthan
addLesson(6, "Exercise : 6/100 - Unification and Integration of Rajasthan", "Rajasthan History", [
  "The political integration of Rajasthan into the democratic fabric of independent India stands as an extraordinary achievement of statesmanship, constitutional diplomacy, and visionary leadership. Prior to August 1947, the region was officially designated by British colonial authorities as Rajputana, an intricate political mosaic comprising nineteen sovereign princely states, three independent chiefships (Lawa, Neemrana, and Kushalgarh), and the centrally administered British enclave of Ajmer-Merwara. These princely territories varied vastly in geographic extent, financial stability, military capability, and administrative development. Integrating these autonomous rulers into a unified modern democratic state was orchestrated masterfully by India Iron Man, Sardar Vallabhbhai Patel, and the astute Secretary of the Ministry of States, V. P. Menon.",
  "The grand unification of Rajasthan was accomplished through seven distinct historical stages between 1948 and 1956. The first stage commenced on March 18, 1948, with the establishment of the Matsya Union, bringing together the four eastern states of Alwar, Bharatpur, Dholpur, and Karauli, with Alwar serving as its administrative capital. Shortly thereafter, the second stage witnessed the creation of Rajasthan Union on March 25, 1948, integrating nine southeastern princely states including Banswara, Bundi, Dungarpur, Jhalawar, Kishangarh, Kota, Pratapgarh, Shahpura, and Tonk, alongside Kushalgarh chiefship, with Maharao Bhim Singh of Kota sworn in as Rajpramukh.",
  "The third stage, known as the United State of Rajasthan, materialized on April 18, 1948, when the historic and prestigious state of Mewar (Udaipur) merged into the union. Pandit Jawaharlal Nehru inaugurated this expanded entity in Udaipur, appointing Maharana Bhupal Singh as Rajpramukh and Manikya Lal Verma as Prime Minister. The fourth stage represented the pivotal breakthrough on March 30, 1949, when the four largest desert kingdoms—Jaipur, Jodhpur, Bikaner, and Jaisalmer—joined the union, creating Greater Rajasthan (Brihat Rajasthan). Sardar Patel formally inaugurated this historic milestone in Jaipur, appointing Maharaja Sawai Man Singh II of Jaipur as Rajpramukh and Hiralal Shastri as the first Chief Minister. Ever since, March 30 is commemorated annually across the state as Rajasthan Day (Rajasthan Diwas).",
  "The fifth stage occurred on May 15, 1949, when the Matsya Union was amalgamated into Greater Rajasthan following the recommendations of the Dr. Shankarrao Deo Committee, establishing the United State of Greater Rajasthan. The sixth stage occurred on January 26, 1950, coinciding with the enforcement of the Constitution of India, when Sirohi state (excluding Abu and Delwara tehsils) was integrated into Rajasthan. The seventh and final stage took effect on November 1, 1956, based on the landmark recommendations of the States Reorganisation Commission headed by Justice Fazal Ali. Under this conclusive reorganization, the centrally administered territory of Ajmer-Merwara, the Abu and Delwara regions of Sirohi, and the Sunel Tappa enclave of Madhya Pradesh were formally integrated into Rajasthan, while the Sironj sub-district was transferred to Madhya Pradesh.",
  "This monumental political consolidation established the territorial boundaries of contemporary Rajasthan, comprising twenty-six administrative districts in 1956. Understanding the chronological sequence, covenant conditions, privy purse provisions, and constitutional transitions of these seven stages is essential for ministerial civil servants. Administrative clerks in the General Administration Department (GAD) and Revenue Department frequently process historical land grants (Jagir resumptions), princely covenant records, and inter-state boundary agreements that trace directly back to these integration treaties. The integration of Rajasthan reflects the triumph of democratic aspirations, turning feudal monarchies into a vibrant, unified state committed to social equity, constitutional democracy, and progressive governance.",
  "Furthermore, the merger required establishing a unified civil service, harmonizing divergent princely revenue laws, standardizing court jurisdictions under the Rajasthan High Court at Jodhpur, and integrating regional police forces into the unified Rajasthan Police. Civil servants played a foundational role in re-cataloguing state treasury assets, establishing district collectorates, and extending democratic adult franchise into rural hamlets. The unification of Rajasthan remains one of the greatest administrative triumphs in modern Indian history."
]);

// 7. Panchayati Raj System and Nagaur Milestone
addLesson(7, "Exercise : 7/100 - Panchayati Raj System and Nagaur Milestone", "Polity & Governance", [
  "Rajasthan holds a revered and pioneering position in the constitutional and democratic history of modern India as the historic birthplace of the institutionalized Panchayati Raj system. On October 2, 1959, commemorating the birth anniversary of Mahatma Gandhi, the first Prime Minister of independent India, Pandit Jawaharlal Nehru, officially inaugurated the three-tier system of local rural self-government at Nagaur district in Rajasthan. This historic event marked the practical realization of Article 40 of the Directive Principles of State Policy, which commands the state to organize village panchayats and endow them with such powers and authority as may be necessary to enable them to function as units of self-government.",
  "The conceptual architecture of democratic decentralization in India was formulated by the Balwant Rai Mehta Committee, appointed by the National Development Council in 1957. The committee recommended an organically linked, three-tier institutional structure comprising the Gram Panchayat at the village level, the Panchayat Samiti at the block level, and the Zila Parishad at the district level. Rajasthan proactively embraced these visionary recommendations by enacting the historic Rajasthan Panchayat Samitis and Zila Parishads Act in 1959. Andhra Pradesh soon followed suit, but Rajasthan earned the everlasting distinction of being the first state to transfer genuine executive powers, developmental funds, and administrative authority to elected rural representatives.",
  "To strengthen grassroots democracy and remedy administrative deficiencies, several high-powered committees subsequently reviewed local governance frameworks, including the Ashok Mehta Committee in 1977, the G. V. K. Rao Committee in 1985, and the L. M. Singhvi Committee in 1986. The landmark 73rd Constitutional Amendment Act of 1992 imparted enduring constitutional status to Panchayati Raj Institutions (PRIs) by inserting Part IX and the Eleventh Schedule into the Indian Constitution, specifying twenty-nine distinct developmental subjects transferred to rural local bodies, such as agriculture, minor irrigation, drinking water, rural housing, and poverty alleviation programs.",
  "In Rajasthan, the Panchayati Raj framework is governed by the Rajasthan Panchayati Raj Act of 1994 and its accompanying statutory rules. The state has been at the forefront of progressive electoral reforms, introducing affirmative reservations for Scheduled Castes, Scheduled Tribes, and Other Backward Classes, alongside a historic fifty percent reservation for women across all tiers of local bodies. Furthermore, the mandatory convening of the Ward Sabha and Gram Sabha ensures direct citizen participation, social audit of developmental expenditures, transparent selection of welfare beneficiaries, and scrutiny of public works executed under the Mahatma Gandhi National Rural Employment Guarantee Scheme (MGNREGS).",
  "For clerical staff working within the Panchayati Raj and Rural Development Department, Zila Parishads, and Panchayat Samitis, administrative responsibilities are multifaceted and impactful. Lower Division Clerks process development sanction orders, maintain cashbooks, audit expenditure vouchers, update the e-Gram Swaraj national portal, and assist Village Development Officers (VDOs) and Block Development Officers (BDOs). Thorough knowledge of statutory financial rules, tender procurement processes, muster roll verification, and public grievance mechanisms enables clerical personnel to uphold fiscal transparency and prevent leakages in rural welfare delivery.",
  "Modern Panchayati Raj governance in Rajasthan increasingly leverages digital public infrastructure, such as the Jan Soochna Portal and geospatial planning tools, to ensure real-time tracking of asset creation in rural habitations. Empowering elected representatives through structured training programs conducted by the Indira Gandhi Panchayati Raj and Gramin Vikas Sansthan (IGPRS) in Jaipur fosters administrative leadership among rural women and marginalized communities. Grassroots local self-government remains the lifeblood of rural empowerment, poverty reduction, and participative democracy across the desert and tribal villages of Rajasthan."
]);

// 8. Major River Basins and Water Bodies of Rajasthan
addLesson(8, "Exercise : 8/100 - Major River Basins and Water Bodies of Rajasthan", "Rajasthan Geography", [
  "Due to its unique physical geography, prominent central Aravalli ridge, and distinct climatic zones, Rajasthan features a complex hydrological drainage network divided into three major categories: rivers flowing eastward to drain into the Bay of Bengal, rivers flowing westward or southward to drain into the Arabian Sea, and an extensive network of inland drainage streams that disappear into desert sands. Accounting for nearly 10.4 percent of India total geographical area, Rajasthan possesses barely 1.16 percent of the country total surface water resources, making scientific watershed management, river basin conservation, and reservoir management matters of critical administrative priority.",
  "The Bay of Bengal drainage system is spearheaded by the Chambal river, the only perennial river of Rajasthan. Originating from the Singar Chauri peak in the Janapav hills of Madhya Pradesh, the Chambal enters Rajasthan near Chaurasigarh in Chittorgarh district, flowing through Kota, Bundi, Sawai Madhopur, Karauli, and Dholpur before merging with the Yamuna in Uttar Pradesh. Renowned for its dramatic gorges and deep ravines, the Chambal river system hosts the monumental Chambal Valley Hydroelectric Project, comprising four major dams: Gandhi Sagar in Madhya Pradesh, Rana Pratap Sagar at Rawatbhata, Jawahar Sagar, and the Kota Barrage. Its primary left-bank tributary, the Banas river—traditionally called 'Van Ki Asha' or Hope of the Forest—originates in the Khamnore hills near Kumbhalgarh, flowing entirely within Rajasthan for about five hundred twelve kilometres before joining the Chambal at Rameshwaram Ghat.",
  "The Arabian Sea drainage system comprises the Luni, Sabarmati, and Mahi rivers. The Luni river is the lifeline of the arid western Thar Desert, originating in the Nag Pahar hills near Ajmer as the Sagarmati. It flows southwest through Nagaur, Jodhpur, Pali, Barmer, and Jalore before discharging into the Rann of Kutch in Gujarat. A unique hydrological characteristic of the Luni is that its water remains sweet and potable up to Balotra in Barmer, after which it turns highly saline due to excessive salt deposits in the desert soil. The Mahi river originates from the Vindhyan hills in Madhya Pradesh, traverses Banswara and Pratapgarh in a distinct U-shaped curve that crosses the Tropic of Cancer twice, and flows into the Gulf of Khambhat, impounded by the massive Mahi Bajaj Sagar Dam.",
  "Inland drainage covers nearly sixty percent of Rajasthan territory, where seasonal streams lack sufficient gradient and water volume to reach the sea. Prominent inland rivers include the Kantli flowing through Sikar and Jhunjhunu, the Sabi originating in the Sewar hills of Jaipur, the Ruparel flowing through Alwar and Bharatpur, and the Ghaggar river in the north. The Ghaggar, often identified with the ancient Vedic river Saraswati, originates in the Shivalik hills of Himachal Pradesh and flows through Hanumangarh and Sri Ganganagar, occasionally reaching Fort Abbas in Pakistan during heavy monsoon flash floods.",
  "Rajasthan is also adorned with historic freshwater and saline lakes that have supported civilizations for millennia. Sambhar Salt Lake, located at the intersection of Jaipur, Nagaur, and Ajmer, is India largest inland saline lake and a designated Ramsar wetland site, producing approximately nine percent of the nation total salt. Pristine freshwater lakes such as Lake Pichola, Fateh Sagar, Jaisamand (Dhebar Lake), Rajsamand, Ana Sagar in Ajmer, and Nakki Lake in Mount Abu represent historic marvels of hydraulic engineering. Lower Division Clerks in the Water Resources Department, Public Health Engineering Department (PHED), and Revenue Department play an indispensable role in maintaining dam storage logs, canal water allocations, and flood emergency registers.",
  "Effective river basin planning, inter-basin water transfers, and groundwater recharge programs are critical for the socio-economic future of Rajasthan. Administrative staff must ensure compliance with environmental flow norms, prevent illegal sand mining along dry riverbeds, and coordinate inter-departmental efforts under the State Water Policy to safeguard every precious drop of surface water for drinking, agriculture, and industry."
]);

// 9. Folk Dances and Performing Arts of Rajasthan
addLesson(9, "Exercise : 9/100 - Folk Dances and Performing Arts of Rajasthan", "Art & Culture", [
  "The vibrant cultural soul, colourful social tapestry, and artistic genius of Rajasthan are vividly expressed through its rich repertoire of folk dances, theatrical performances, and musical traditions. Shaped by diverse royal patronages, desert nomadic traditions, spiritual devotion, and pastoral festivities, Rajasthani folk dances represent an extraordinary synthesis of graceful body movements, rhythmic footwork, dazzling traditional attire, and captivating percussion music. These performing arts have earned worldwide admiration and institutional recognition, serving as living treasures of India intangible cultural heritage.",
  "Ghoomar is widely celebrated as the state dance of Rajasthan and the crown jewel of its performing arts. Traditionally performed exclusively by women on auspicious festivals such as Gangaur and Teej, Ghoomar derives its name from 'Ghoomna', referencing the graceful circular twirling movements of the dancers. Donning brightly coloured flowing skirts known as Ghaghras and shimmering Odhnis, dancers execute synchronized pirouettes, rhythmic hand clapping, and graceful wrist inflections to the accompaniment of traditional instruments like the Dhol, Nagada, and Shehnai. Historically nurtured within the royal palaces of Rajput royalty, Ghoomar has transcended courtly origins to become an integral element of celebratory social gatherings across all strata of Rajasthani society.",
  "In 2010, the Kalbelia folk dance and songs of Rajasthan were inscribed on the Representative List of the Intangible Cultural Heritage of Humanity by UNESCO. Performed by the Kalbelia snake-charmer community, the dance is famous for its breathtaking serpentine flexibility, electrifying tempo, and acrobatic brilliance. Dressed in striking black embroidered flared garments adorned with mirror work and silver thread, female dancers imitate the fluid, rhythmic gliding movements of a serpent. The musical accompaniment is driven by the haunting drone of the Poongi (traditional wind instrument), supported by the Daf, Khanjari, and Dholak. Renowned folk artists such as Gulabo Sapera have showcased Kalbelia dance on prestigious global stages, bringing international acclaim to Rajasthan folk traditions.",
  "Rajasthan is also famous for thrilling occupational and regional folk dances. The Chari dance of Kishangarh, practiced predominantly by the Gujjar community, features women balancing brass pots with burning cotton seeds on their heads while executing delicate foot movements. The Terah Taali dance, performed by women of the Kamada community during the sacred fair of Baba Ramdevji, is a mesmerizing devotional spectacle where dancers tie thirteen brass cymbals (Manjeeras) to their bodies and strike them in rapid rhythmic harmony while performing intricate domestic chores and holding swords in their teeth. In the Shekhawati region, the energetic Gindar dance and Chang dance dominate Holi festivities, while the Bhil tribe of Mewar performs the ancient ritualistic Gauri dance drama.",
  "The Fire dance (Agni Nritya), executed by the Jasnathi sect in Bikaner, presents an awe-inspiring spectacle where devout ascetics dance barefoot over glowing embers of burning wood to the rhythmic chants of 'Fateh Fateh'. From an administrative and cultural governance standpoint, the Department of Art and Culture, the Rajasthan Sangeet Natak Akademi, and the West Zone Cultural Centre (WZCC) at Udaipur play a crucial role in preserving these folk arts. Clerks and administrative officers manage artist welfare schemes, process pension files for senior folk artists, organize state cultural festivals, and facilitate international cultural exchange delegations.",
  "Preserving and promoting traditional performing arts provides sustainable livelihood opportunities for rural folk musicians, hereditary bards (Manganiyars and Langas), and tribal performers. Incorporating folk performances into heritage tourism circuits, desert festivals, and state ceremonial functions reinforces regional identity, enriches cultural tourism, and preserves the vibrant artistic traditions of Rajasthan for future generations."
]);

// 10. E-Governance and Jan Soochna Portal in Rajasthan
addLesson(10, "Exercise : 10/100 - E-Governance and Jan Soochna Portal in Rajasthan", "E-Governance", [
  "The state of Rajasthan has emerged as a visionary pioneer in the nationwide digital governance revolution by fundamentally transforming public administration through transparent, accountable, and citizen-centric information technology systems. Modern e-governance seeks to replace traditional bureaucratic hurdles, physical paperwork, and manual delays with seamless, automated, and paperless public service delivery. The Department of Information Technology and Communication (DoIT&C) has architected an extensive digital ecosystem designed to bring government services directly to the doorsteps of millions of citizens across urban cities and remote rural panchayats.",
  "A monumental milestone in Rajasthan digital transparency journey is the landmark launch of the Jan Soochna Portal in September 2019. Conceptualized as an unprecedented institutional mechanism under Section 4(2) of the Right to Information Act 2005, the Jan Soochna Portal mandates the proactive, suo motu disclosure of government information in the public domain. Unlike traditional RTI procedures that require citizens to submit written applications, pay fees, and wait thirty days for replies, the Jan Soochna Portal empowers any citizen to instantly access comprehensive public welfare data online without filing any application. Today, the portal hosts real-time information on hundreds of government schemes across dozens of departments, covering public distribution rations, social security pensions, MGNREGS job cards, land records, and mining leases.",
  "Complementing the Jan Soochna Portal is the Rajasthan Single Sign-On (RajSSO) digital identity framework, which provides a unified, secure authentication gateway for citizens, government employees, and business enterprises. Through a single SSO ID, users can seamlessly access an extensive suite of administrative applications, including RajKaj (integrated enterprise office workflow), e-Mitra (citizen service delivery platform), Shala Darpan (school education monitoring), and the Integrated Financial Management System (IFMS). For government employees, RajKaj has digitized the entire lifecycle of official correspondence, including file tracking, electronic noting, annual performance appraisal reports (APAR), leave applications, and property return submissions.",
  "The e-Mitra digital delivery network represents one of the largest public-private partnership (PPP) service networks in India. With tens of thousands of active kiosks operating across every gram panchayat and urban ward, e-Mitra enables citizens to pay electricity and water bills, apply for caste and domicile certificates, register births and deaths, and enroll in government welfare schemes without visiting government offices. This decentralized digital infrastructure eliminates intermediaries, curtails administrative corruption, and ensures equitable access to essential public utilities for vulnerable rural populations.",
  "For Lower Division Clerks (LDCs) and junior administrative officers in Rajasthan government secretariats, mastery of e-governance platforms is indispensable for daily office workflows. Clerks must efficiently process electronic files on RajKaj, verify digital signatures, manage secure citizen databases, validate Aadhaar and Jan Aadhaar beneficiary credentials, and monitor online grievances registered on the Rajasthan Sampark portal. Prompt file disposal, accurate electronic indexing, and timely redressing of citizen complaints are monitored through automated digital dashboards reviewed directly by District Collectors and the Chief Secretary.",
  "By fostering transparency, eliminating bureaucratic opacity, and democratizing access to public information, Rajasthan digital governance initiatives have set a national benchmark for responsive democratic administration. Sustained investment in digital literacy, rural broadband connectivity via RajNET, and cyber security safeguards will ensure that e-governance continues to empower citizens and elevate administrative productivity to global standards."
]);

console.log('Tested 10 lessons. Word counts:');
lessons.forEach(l => console.log(l.id, l.words));
