const fs = require('fs');
const path = require('path');

const extraBatch4 = {
  61: `Moreover, the promotion of eco-friendly wool dyeing using natural plant extracts from desert vegetation has opened profitable export avenues in European organic carpet markets. Shepherds cooperatives collaborate with state veterinary universities to conduct selective breeding programs that enhance both fleece quality and sheep liveweight. Clerical personnel in district animal husbandry collectorates maintain records of pasture development grants and process insurance claims for disease-affected flocks, sustaining the pastoral wool ecosystem of Rajasthan.`,
  62: `Additionally, India Post Payments Bank has partnered with state cooperative banks and regional rural institutions to enable inter-operable cash management for small business traders in remote market yards. Organizing village financial literacy camps and educating rural women on mobile banking security prevents debit fraud and protects family savings. Dedicated postal banking services ensure that formal banking amenities reach every remote hamlet across the desert plains of Rajasthan.`,
  63: `Furthermore, state administrative reforms departments conduct periodic independent audits to evaluate public awareness and institutional compliance with published Citizen Charters. Public service delivery points that consistently achieve zero pendency rates are recognized with state excellence awards, motivating civil servants to maintain high standards of civic responsiveness. Adhering strictly to Citizen Charters upholds public trust and transforms state administration into an efficient, citizen-friendly public service machinery.`,
  64: `Moreover, the GeM portal incorporates automated business analytics that detect abnormal bidding patterns and eliminate anti-competitive cartelization among participating contractors. Finance department officers review quarterly departmental procurement trends, ensuring that public funds are utilized with utmost fiscal prudence and complete transparency. GeM has revolutionized public purchasing, delivering significant budget savings and fostering fair commercial competition across Rajasthan.`,
  65: `Additionally, digitized pension tracking portals provide retiring employees with real-time status updates via automated SMS alerts at every stage of pension paper verification. Establishment clerks coordinate with treasury officers to ensure that pension payment orders, retirement gratuity sanctions, and commutation disbursements are finalized prior to the employee last working day, ensuring a smooth transition into retirement for dedicated public servants.`,
  66: `Furthermore, departmental vigilance committees conduct periodic reviews of office procedures to identify systemic vulnerabilities and eliminate opportunities for corruption or administrative harassment. Fostering an institutional environment of transparency, ethical accountability, and mutual respect elevates the reputation of the civil service and inspires public confidence in democratic governance across Rajasthan.`,
  67: `Additionally, urban local bodies are adopting green municipal budgeting and energy-efficient LED street lighting programs, significantly curtailing municipal electricity expenditures while cutting carbon emissions. Ministerial personnel maintain ward development expenditure ledgers, audit commercial trade licensing fees, and coordinate public consultations on town planning schemes, ensuring that urban expansion proceeds in an orderly and sustainable manner.`,
  68: `Moreover, architectural conservation teams utilize non-destructive ultrasonic testing and digital photogrammetry to monitor structural stability and restore delicate stone carvings along ancient stepwell walls. Rejuvenating historical subterranean stepwells honors Rajasthan timeless water management wisdom and inspires modern civil engineers to integrate traditional rainwater harvesting principles into urban water infrastructure.`,
  69: `Additionally, scientific monitoring using satellite telemetry and automated sand traps allows CAZRI researchers to quantify wind erosion rates and evaluate the long-term effectiveness of vegetative shelterbelts along desert highways. Forest department personnel maintain nurseries of drought-hardy native saplings, distributing millions of seedlings to rural farming communities to expand protective vegetative cover across the Thar Desert.`,
  70: `Furthermore, state horticulture extension officers conduct regular field demonstrations on integrated nutrient management and biological pest control in protected polyhouses, helping farmers reduce chemical pesticide usage. Expanding protected cultivation across desert districts transforms traditional farming into a profitable, climate-resilient enterprise that delivers prosperity to rural farming families across Rajasthan.`,
  71: `Moreover, state veterinary departments organize specialized mobile treatment camps during seasonal disease outbreaks, providing free prophylactic vaccinations and mineral supplements to camel herds across the Thar Desert. Promoting camel milk cooperatives and supporting traditional pastoralist lineages preserves the cultural identity and ecological biodiversity of western Rajasthan for future generations.`,
  72: `Additionally, the establishment of nursing colleges and paramedical training institutes attached to newly created medical colleges ensures an adequate supply of trained healthcare professionals for district hospitals. Ministerial personnel maintain hospital accreditation dockets, audit high-end medical equipment maintenance contracts, and track clinical care outcomes, ensuring that advanced tertiary healthcare remains accessible to all citizens.`,
  73: `Furthermore, mobile health vans equipped with satellite internet connectivity and point-of-care diagnostic analyzers regularly visit remote tribal hamlets, bringing tele-consultation facilities directly to vulnerable populations. Ministerial staff monitor tele-radiology service quality, verify diagnostic data transmission logs, and process equipment maintenance claims, ensuring continuous, high-quality digital healthcare delivery.`,
  74: `Moreover, automated data synchronization between Shala Darpan and state treasury systems ensures that scholarships, incentive awards, and teacher salaries are credited directly to beneficiary bank accounts without administrative delays. Continuous technological enhancement of Shala Darpan reinforces educational transparency, empowering teachers, students, and parents across Rajasthan.`,
  75: `Additionally, state university incubation centers collaborate with national scientific funding agencies to provide startup seed capital and patent assistance to promising student researchers. Administrative personnel in higher education secretariats coordinate academic audit committees, verify university grant utilization certificates, and manage student welfare funds, fostering an environment of academic excellence and intellectual innovation.`,
  76: `Furthermore, collaborating with national archival networks and international academic universities allows the Rajasthan State Archives to host global seminars on medieval Indian history and paleography. Digital access to ancient manuscripts preserves documentary evidence of historical land rights and royal treaties, enriching historical scholarship and protecting cultural heritage for all humanity.`,
  77: `Moreover, state departments enforce strict ethical guidelines governing the administrative use of artificial intelligence, requiring human supervisory review of all automated draft decisions and ensuring complete algorithm explainability. Training ministerial staff in modern computational tools and data verification protocols transforms public administration into a transparent, agile, and citizen-centered governance ecosystem.`,
  78: `Additionally, community eco-development committees established around Mukundra Hills Tiger Reserve receive financial assistance to construct community water harvesting ponds and establish solar-powered agricultural fencing, mitigating human-wildlife conflict along park boundaries. Protecting contiguous wildlife corridors preserves apex carnivore populations and maintains the ecological balance of Rajasthan deciduous forests.`,
  79: `Furthermore, random food quality sampling conducted by certified public health laboratories ensures that every subsidized meal served at Indira Rasois meets strict nutritional and microbiological standards. Ministerial personnel verify vendor billing dockets, track kitchen utility expenses, and monitor citizen satisfaction ratings, ensuring that the state humanitarian commitment to eradicate hunger is fulfilled with exemplary dignity.`,
  80: `Moreover, federation of women self-help groups into cooperative producer companies enables rural women to access bulk packaging machinery, cold storage facilities, and organized retail markets for their agricultural and artisanal products. Administrative staff in rural development directorates audit micro-credit disbursements, maintain member training registries, and support rural women in building sustainable, profitable collective enterprises across Rajasthan.`
};

let code = fs.readFileSync(path.join(__dirname, 'generate_batch4.cjs'), 'utf8');

for (const [idStr, para] of Object.entries(extraBatch4)) {
  const id = parseInt(idStr);
  const regex = new RegExp(`(addLesson\\(${id},[\\s\\S]*?\\[[\\s\\S]*?)(\\n\\]\\);)`);
  const match = code.match(regex);
  if (match) {
    const replacement = `${match[1]},\n  \`${para.replace(/`/g, '\\`')}\`${match[2]}`;
    code = code.replace(regex, replacement);
    console.log(`Patched extra into Batch 4 Lesson ${id}`);
  } else {
    console.error(`Could not match Lesson ${id}`);
  }
}

fs.writeFileSync(path.join(__dirname, 'generate_batch4.cjs'), code, 'utf8');
console.log('Successfully patched Batch 4!');
