const fs = require('fs');
const path = require('path');

const extraBatch2 = {
  21: `Additionally, network performance monitoring tools help administrative teams maintain bandwidth optimization across ministerial departments. Clerks should avoid bandwidth-heavy non-official streaming during peak office hours to preserve bandwidth for critical treasury transactions and video conferences. Regular network security audits conducted by designated system administrators ensure that network routers, hardware firewalls, and proxy gateways operate with updated security firmware, shielding public administration from external distributed denial-of-service (DDoS) threats.`,
  22: `Moreover, coordination between the State Secretariat and the Legislative Assembly (Vidhan Sabha) during legislative sessions demands intense clerical activity. Ministerial clerks in Secretariat branches prepare answers to starred and unstarred legislative questions, compile administrative statistical statements, and verify factual details within stringent deadlines. Upholding administrative neutrality, confidentiality, and procedural accuracy allows the Secretariat to function as the bedrock of constitutional democracy in Rajasthan.`,
  23: `Furthermore, mobile health outreach teams equipped with diagnostic vans routinely visit remote desert settlements and tribal hamlets to conduct health check-ups and distribute free medicines. Clerical personnel in chief medical and health offices (CMHO) reconcile outpatient registers, process medical equipment maintenance logs, and manage public awareness drives for seasonal immunizations, ensuring comprehensive healthcare access across rural Rajasthan.`,
  24: `Additionally, the state climate change action plan integrates meteorological forecasting with district disaster preparedness frameworks. Agricultural extension officers guide farmers on adopting micro-irrigation systems, sprinkler sets, and drought-tolerant seed varieties to adapt to erratic rainfall variations. Clerical staff in district emergency operations centers maintain daily weather logs and track monsoon rainfall departures, supporting swift administrative relief measures during natural calamities.`,
  25: `Furthermore, traditional manuscript preservation techniques, such as herbal fumigation using neem leaves and archival paper restoration, protect historic miniature folios from biological decay. The Department of Archaeology collaborates with master miniaturists to conduct public workshops and art apprenticeships for younger generations. Preserving these vibrant visual arts reinforces Rajasthan global stature as a flourishing sanctuary of traditional Indian culture.`,
  26: `Additionally, the transition to electronic file management under RajKaj enables automated reminder alerts for pending dockets and seamless cross-referencing of historical decisions. Clerks must ensure that confidential and secret documents receive appropriate digital encryption tags and restricted access permissions. Meticulous document indexing and structured archiving uphold institutional integrity and facilitate timely public service delivery.`,
  27: `Furthermore, government departments conduct periodic cyber mock drills to assess employee readiness against sophisticated social engineering and ransomware simulations. Ministerial staff must verify digital certificates before processing electronic financial payments, report phishing emails promptly to IT administrators, and never disable system antivirus protection. Practicing vigilant cyber hygiene guarantees the uninterrupted safety of Rajasthan e-governance infrastructure.`,
  29: `Moreover, utilizing interactive slide navigation features, such as custom action buttons and hyperlinks, enables presenters to transition smoothly between detailed budgetary annexures and high-level summaries during executive briefings. Clerks must ensure that all presented data charts are properly labeled with clear units of measurement and authentic data sources, providing senior policymakers with reliable visual evidence for informed decision-making.`,
  32: `Additionally, the establishment of dedicated petroleum engineering academic programs at state universities and technical training institutes equips local youth with specialized skills for exploration and refining careers. Ministerial personnel in industrial development directorates coordinate land allotments for downstream petrochemical ancillary units, promoting regional manufacturing growth and local employment opportunities.`,
  33: `Furthermore, modern design collaborations between traditional master artisans and national fashion institutes have revitalized global interest in Rajasthani block prints, blue pottery, and leather mojaris. Establishing common facility centers equipped with testing laboratories and modern dye vats helps rural artisans maintain uniform international quality standards while preserving their rich ancestral craftsmanship.`,
  34: `Additionally, the integration of the Rajasthan Sampark citizen grievance redressal portal with mobile messaging platforms allows citizens to receive instant SMS updates regarding the progress of their service applications and complaints. Administrative clerks review pending cases daily on digital monitoring dashboards, ensuring that public grievances receive speedy, impartial, and transparent resolution.`,
  36: `Furthermore, maintaining strict reconciliation between departmental cash book balances and state treasury passbooks at the end of every calendar month prevents unverified financial liabilities. Clerks must prepare monthly expenditure statements (Form GA 19) for submission to administrative departments and finance officers, ensuring that public funds are utilized efficiently and transparently within approved budgetary authorizations.`,
  37: `Additionally, state remote sensing scientists collaborate with urban planning bodies to monitor urban sprawl, delineate municipal green belts, and model surface flood runoff channels in growing metropolitan areas like Jaipur, Jodhpur, and Kota. Utilizing satellite technology enables evidence-based town planning and sustainable natural resource management across the state.`,
  38: `Furthermore, the cooperative dairy network operates specialized cattle feed manufacturing plants and automated fodder seed distribution centers to support rural livestock nutrition. Lower Division Clerks process veterinary equipment procurement files, maintain milk chilling center maintenance dockets, and audit member bonus payouts, reinforcing the sustainable economic prosperity of rural farming communities.`,
  39: `Additionally, the preservation of astronomical instruments at Jantar Mantar involves specialized conservation architects who utilize non-abrasive natural lime plasters and gentle cleaning techniques to preserve ancient marble quadrant calibrations without altering instrument alignments. Educational workshops conducted at the site inspire young students to explore the mathematical beauty of celestial astronomy.`,
  40: `Furthermore, consumer clubs established in secondary schools and colleges across Rajasthan actively educate young students on product expiry verification, packaged commodity rules, and digital payment dispute procedures. Ministerial staff in consumer commissions organize mobile consumer awareness exhibitions, empowering rural and urban citizens alike to demand fair trade practices and quality consumer goods.`
};

let code = fs.readFileSync(path.join(__dirname, 'generate_batch2.cjs'), 'utf8');

for (const [idStr, para] of Object.entries(extraBatch2)) {
  const id = parseInt(idStr);
  const regex = new RegExp(`(addLesson\\(${id},[\\s\\S]*?\\[[\\s\\S]*?)(\\n\\]\\);)`);
  const match = code.match(regex);
  if (match) {
    const replacement = `${match[1]},\n  \`${para.replace(/`/g, '\\`')}\`${match[2]}`;
    code = code.replace(regex, replacement);
    console.log(`Patched extra into Batch 2 Lesson ${id}`);
  } else {
    console.error(`Could not match Lesson ${id}`);
  }
}

fs.writeFileSync(path.join(__dirname, 'generate_batch2.cjs'), code, 'utf8');
console.log('Successfully patched Batch 2!');
