const fs = require('fs');
const path = require('path');

const extraParas = {
  5: `Moreover, computer ergonomics and preventive hardware maintenance are vital for sustaining administrative efficiency. Ensuring adequate ventilation for CPU cabinets, periodically cleaning keyboard membranes, and positioning display monitors at eye level minimizes physical fatigue among ministerial data entry operators. Understanding uninterrupted power supply (UPS) ratings, surge suppressors, and proper system shutdown procedures safeguards system motherboards and solid-state drives against electrical voltage spikes. Through regular diagnostic scans and adherence to standard IT security protocols, clerical personnel maintain reliable desktop hardware ecosystems that support seamless digital administration.`,
  7: `Furthermore, social audits conducted during Gram Sabha sessions provide a transparent mechanism for villagers to scrutinize public procurement bills, verify construction materials used in community buildings, and review muster roll attendance. Under the Rajasthan Guaranteed Delivery of Public Services Act, Panchayat officials must adhere to strict delivery timelines for issuing land tenancy extracts, water connection clearances, and rural trade permits. By embedding real-time tracking and public social audits into grassroots governance, Rajasthan Panchayati Raj institutions empower rural citizens and ensure that public developmental funds foster inclusive rural transformation.`,
  8: `Additionally, the conservation of historic stepwells (Baoris), community check dams (Johads), and traditional percolation tanks across rural Rajasthan revitalizes depleted subterranean aquifers. The state government actively collaborates with local village water and sanitation committees (VWSC) to maintain irrigation sluice gates, prevent industrial effluent dumping into natural riverbeds, and execute catchment desiltation before the onset of the monsoon. Diligent monitoring of river gauge readings and lake storage reserves by ministerial staff ensures equitable water allocations for municipal, agricultural, and industrial stakeholders throughout the year.`,
  9: `Moreover, the preservation of traditional puppet theater (Kathputli) of the Bhat community forms an integral chapter of Rajasthan artistic heritage. Accompanied by the shrill whistle (Boli) and rhythmic beats of the Dholak, wooden marionettes narrate chivalric ballads of Amar Singh Rathore and historical legends with witty social commentary. The Department of Art and Culture provides institutional platforms and welfare grants to folk puppeteers and balladeers, ensuring that these centuries-old visual and performing art forms continue to delight domestic and international audiences while enriching the cultural tapestry of the state.`,
  10: `Additionally, the state data center (SDC) in Jaipur provides a secure, cloud-enabled hosting environment for hundreds of departmental e-governance applications, safeguarded by multi-tier firewalls and 24/7 cyber security operations centers. Ministerial staff must practice rigorous data hygiene, adhering to password rotation policies, multi-factor authentication, and safe digital document transmission protocols. By ensuring that public databases remain resilient, transparent, and instantly accessible, Rajasthan digital governance architecture establishes a national benchmark for citizen empowerment and responsive public administration.`,
  11: `Furthermore, understanding basic command-line shell utilities and batch scripting provides administrative personnel with powerful troubleshooting options when graphical desktop interfaces encounter unexpected errors. Clerks can verify active network connections using ping and ipconfig, check disk integrity through chkdsk, and view running background system tasks through tasklist commands. Regular maintenance routines, such as clearing temporary internet caches, defragmenting physical hard drives, and verifying antivirus signature updates, ensure that office computer systems operate at peak responsiveness and maintain high productivity.`,
  12: `Moreover, the promotion of green hydrogen production and battery energy storage systems (BESS) represents the next frontier in Rajasthan clean energy roadmap. Harnessing surplus daytime solar generation to produce green hydrogen and charge utility-scale storage batteries ensures continuous grid stability during evening peak demand periods. Clerical personnel in the renewable energy sector handle statutory lease documentation, grid connectivity compliance filings, and environmental impact clearance records, actively supporting Rajasthan ambition to remain India foremost green energy powerhouse for decades to come.`,
  13: `Furthermore, the state mineral policy prioritizes value addition and mineral beneficiation within Rajasthan boundaries, discouraging the export of unprocessed raw ores. Establishing modern mineral grinding units, marble slurry processing plants, and ceramic clusters generates local industrial employment and maximizes regional economic returns. Mining department clerks maintain rigorous audit trails of royalty receipts, mineral transport permits (e-Ravanna), and boundary demarcation maps, ensuring that mineral extraction proceeds in strict accordance with statutory environmental guidelines and sustainable resource management principles.`,
  14: `Moreover, the fearless contributions of women freedom fighters in Rajasthan deserve everlasting national tribute. Heroines such as Ratna Shastri, Kishori Devi, Shanta Trivedi, and Janaki Devi Bajaj defied feudal purdah customs, organized boycotts of foreign goods, led anti-liquor picketing campaigns, and suffered rigorous imprisonments with undaunted courage. Their heroic activism catalyzed profound social reforms across peasant households, advancing girls education and community upliftment while cementing the democratic foundations of post-independence Rajasthan.`,
  15: `Furthermore, mastering Microsoft Word keyboard shortcuts and template automation significantly enhances clerical workflow efficiency. Standard keyboard commands—such as Ctrl+N for new documents, Ctrl+S for saving, Ctrl+P for printing, and Ctrl+K for inserting hyperlinks—allow clerks to navigate complex drafts effortlessly. Creating standardized departmental templates with pre-configured header margins, official emblem watermarks, and statutory citation footers ensures visual uniformity across all official executive orders, notifications, and gazette memoranda issued by government secretariats.`,
  16: `Moreover, community-driven eco-tourism initiatives within wildlife buffer zones provide sustainable alternative livelihoods for forest-dwelling communities. Local youth are trained as certified eco-guides, vehicle drivers, and safari naturalists, transforming local populations into active guardians of national park borders. Clerical staff in forest division collectorates coordinate tourist entry ticketing accounts, wildlife damage insurance settlements, and conservation reserve notifications, ensuring harmonious coexistence between wildlife biodiversity and local socio-economic development.`,
  17: `Furthermore, the adoption of precision agriculture, drone-based pesticide spraying, and solar-powered cold storage units is revolutionizing farming practices across rural Rajasthan. The state agricultural universities in Bikaner, Jodhpur, and Jobner conduct cutting-edge research on climate-resilient crop varieties and arid horticulture techniques. Departmental clerks manage agricultural subsidy ledgers, verify farmer bank account credentials under direct benefit transfer schemes, and compile seasonal crop output digests, directly supporting farming households and reinforcing regional food security.`,
  18: `Additionally, the economic multiplier effects of Rajasthan fairs and festivals extend across the handicraft, hospitality, and transport industries. Local leather artisans selling camel leather footwear (Mojaris), tie-and-dye fabric printers, and terracotta potters earn substantial portions of their annual income during these vibrant cultural gatherings. Clerical staff in district collectorates and tourism departments maintain vendor allotment registries, verify public safety fire permits, and ensure meticulous financial accounting for cultural festival grants, upholding Rajasthan global reputation for regal celebration and warm hospitality.`,
  19: `Furthermore, maintaining strict confidentiality and adherence to file movement registries prevents unauthorized leakage of sensitive policy drafts and government procurement evaluations. Clerks must ensure that every file handed over to another branch is duly recorded in the Transit Register with date and signature acknowledgments. By mastering standardized noting phraseology, verifying statutory precedents, and drafting precise executive orders, ministerial staff ensure that public administration in Rajasthan operates with exemplary legal fidelity, procedural speed, and democratic accountability.`,
  20: `Moreover, mastering keyboard shortcuts and audit formula tracking tools in Microsoft Excel empowers ministerial staff to manage large public datasets with exceptional precision. Utilizing functions like Trace Precedents and Trace Dependents allows clerks to verify complex linked budget formulas before final submission to treasury officers. Automated data sorting, error-checking routines, and conditional highlight rules ensure that financial registers, pension disbursement rolls, and administrative statistics remain mathematically flawless and audit-compliant at all times.`
};

let code = fs.readFileSync(path.join(__dirname, 'generate_batch1.cjs'), 'utf8');

// For each id in extraParas, find `addLesson(id, ... [ ... ])` and insert the extra para
for (const [idStr, para] of Object.entries(extraParas)) {
  const id = parseInt(idStr);
  const regex = new RegExp(`(addLesson\\(${id},[\\s\\S]*?\\[[\\s\\S]*?)(\\n\\]\\);)`);
  const match = code.match(regex);
  if (match) {
    const replacement = `${match[1]},\n  \`${para.replace(/`/g, '\\`')}\`${match[2]}`;
    code = code.replace(regex, replacement);
    console.log(`Patched extra paragraph into Lesson ${id}`);
  } else {
    console.error(`Could not match Lesson ${id}`);
  }
}

fs.writeFileSync(path.join(__dirname, 'generate_batch1.cjs'), code, 'utf8');
console.log('Successfully updated generate_batch1.cjs');
