const fs = require('fs');
const path = require('path');

const extraBatch3 = {
  41: `Additionally, ministerial clerks processing pension papers must ensure that qualifying service verification is completed well in advance of the employee retirement date. Maintaining complete no-dues certificates, vigilance clearance reports, and verified leave accounts prevents delayed pension payment orders (PPO). Operating with procedural diligence and compassion ensures that retiring civil servants receive their statutory terminal benefits seamlessly, upholding the benevolent spirit of state service regulations.`,
  42: `Furthermore, sustainable tourism policies encourage community participation in rural homestays, village crafts walks, and folk music performances, spreading economic benefits beyond metropolitan centers into rustic desert hamlets. The Department of Tourism organizes international travel marts and heritage photography exhibitions to showcase regional architectural wonders, ensuring that Rajasthan regal charm continues to captivate travelers from all corners of the globe.`,
  43: `Moreover, understanding virtual memory concepts and swap file management allows clerks to optimize operating system performance when running memory-intensive database queries. Configuring proper virtual memory paging sizes on system drives prevents application crashes during heavy administrative workloads. Routine disk cleanup and system optimization ensure that office workstations operate at peak computational responsiveness.`,
  44: `Additionally, the state government promotes sustainable stone quarrying through mandatory mine closure plans, scientific topsoil preservation, and compensatory afforestation around quarry perimeters. Establishing automated stone cutting clusters equipped with water recycling systems significantly reduces fresh water consumption and eliminates airborne stone dust, safeguarding worker health while fostering industrial growth across Rajasthan.`,
  45: `Furthermore, the District Collector presides over the District Public Grievance Redressal Committee, holding weekly public hearings to resolve citizen petitions and administrative bottlenecks. Ministerial staff record hearing minutes, track compliance deadlines across executive departments, and communicate disposal orders to complainants, reinforcing responsive and accountable grassroots governance.`,
  46: `Moreover, establishing clear rules for departmental email groups and distribution lists prevents unnecessary email clutter and ensures that administrative circulars reach intended recipients promptly. Clerical staff should periodically archive older email folders into local data files to maintain mailbox storage limits, ensuring seamless communication across government offices.`,
  47: `Additionally, traditional folk songs and devotional Bhajans dedicated to Lok Devtas, sung by village bards during nocturnal Jagrans, serve as living repositories of regional history, dialectal idioms, and social ethics. Preserving these musical traditions through state archives ensures that Rajasthan spiritual heritage inspires future generations.`,
  48: `Furthermore, institutional training programs conducted for village water committees emphasize water conservation, rainwater harvesting, and the protection of local catchment zones from contamination. Public health engineering teams work closely with rural communities to maintain continuous chlorinated water supply, drastically reducing waterborne diseases and improving overall public health across rural Rajasthan.`,
  49: `Additionally, RIICO organizes regular buyer-seller meets and international industrial exhibitions to attract foreign direct investment into specialized manufacturing parks. Dedicated single-window facilitation desks assist industrial investors in obtaining building permissions, power connections, and water allocations within guaranteed statutory timeframes, cementing Rajasthan reputation as an attractive industrial destination.`,
  50: `Moreover, traditional community conservation zones known as Orans, dedicated to local deities, provide vital ecological refuges where grazing and tree-felling are strictly prohibited by custom. Protecting these ancient sacred groves preserves native medicinal herbs and arid wildlife habitats, demonstrating the timeless wisdom of traditional Rajasthani environmental stewardship.`,
  51: `Furthermore, urban local bodies conduct extensive public awareness campaigns involving resident welfare associations, youth volunteers, and schoolchildren to discourage single-use plastics and promote household composting. Recognizing top-performing residential wards with cleanliness awards encourages healthy civic competition, making urban cleanliness a shared community responsibility across the state.`,
  52: `Additionally, smart cities promote sustainable urban mobility by introducing zero-emission electric buses (e-Buses) and establishing multi-modal transit interchange hubs connecting railway stations with public bus networks. Clerical staff handle bus concession registers, coordinate charging infrastructure permits, and maintain public transit ridership databases, supporting sustainable and accessible urban transit for all citizens.`,
  53: `Furthermore, district enterprise facilitation centers provide budding entrepreneurs with mentorship on product packaging, digital marketing, and intellectual property rights registration. Simplifying regulatory compliances and offering generous credit subsidies encourages local youth to establish innovative manufacturing ventures, driving economic diversification across Rajasthan.`,
  54: `Additionally, modern retail partnerships with major e-commerce platforms allow rural Khadi societies to market their handmade woollens, organic honey, and herbal soaps directly to urban consumers nationwide. Ensuring fair remunerative wages to rural spinners and weavers protects traditional craft livelihoods and strengthens the decentralized rural economy.`,
  55: `Furthermore, deploying modern breathalyzers, automated speed interceptor vans, and high-resolution surveillance cameras along accident-prone national highways significantly curtails dangerous driving. Public education campaigns conducted during National Road Safety Month remind drivers that adherence to traffic rules protects human lives and creates safer roadways for all.`,
  57: `Additionally, specialized skill training programs tailored for disabled individuals and vulnerable tribal youth provide customized vocational training and assistive technology support, facilitating inclusive economic integration. Regular industry interaction ensures that training curriculums remain dynamically aligned with evolving technological requirements.`,
  58: `Furthermore, mass athletic festivals create an enduring community spirit, breaking down caste barriers and fostering lasting friendships across village neighborhoods. Identifying and nurturing young sports talent through dedicated rural sports academies paves the way for Rajasthan youth to represent the nation in international sporting arenas.`,
  59: `Additionally, establishing common footwear testing laboratories and raw material distribution depots helps small leather artisans procure quality tanned leather at competitive prices. Promoting export linkages and intellectual property protections for traditional Mojari footwear ensures sustainable livelihood growth for thousands of artisan families across rural Rajasthan.`,
  60: `Furthermore, modern gemological laboratories operated by industry associations in Jaipur provide international grading certifications for colored gemstones and diamonds, assuring global buyers of gemstone authenticity. Continuous innovation in fine jewellery design and gemstone cutting techniques maintains Jaipur historic supremacy in the international luxury jewellery marketplace.`
};

let code = fs.readFileSync(path.join(__dirname, 'generate_batch3.cjs'), 'utf8');

for (const [idStr, para] of Object.entries(extraBatch3)) {
  const id = parseInt(idStr);
  const regex = new RegExp(`(addLesson\\(${id},[\\s\\S]*?\\[[\\s\\S]*?)(\\n\\]\\);)`);
  const match = code.match(regex);
  if (match) {
    const replacement = `${match[1]},\n  \`${para.replace(/`/g, '\\`')}\`${match[2]}`;
    code = code.replace(regex, replacement);
    console.log(`Patched extra into Batch 3 Lesson ${id}`);
  } else {
    console.error(`Could not match Lesson ${id}`);
  }
}

fs.writeFileSync(path.join(__dirname, 'generate_batch3.cjs'), code, 'utf8');
console.log('Successfully patched Batch 3!');
