const fs = require('fs');
const path = require('path');

const extraBatch5 = {
  81: `Additionally, community eco-tourism guides trained by the forest department lead birdwatching groups along designated heritage trails, educating visitors on avian ecology and hypersaline conservation. Scientific monitoring of water quality parameters and strict regulation of industrial effluents ensure that the fragile lake habitat remains healthy for future generations of migratory birds. Sustaining Sambhar Lake balances industrial salt production with international biodiversity conservation in Rajasthan.`,
  82: `Moreover, the introduction of automated ballistics identification systems and voice biometric analysis software accelerates evidence evaluation in sensitive criminal trials. State forensic scientists regularly present expert testimony in high-profile judicial proceedings, providing unbiased scientific evaluations that guide fair judicial decisions. Continuous technological upgrading of forensic infrastructure reinforces public trust in the state criminal justice system across Rajasthan.`,
  83: `Furthermore, mobile Lok Adalats travel to remote tribal tehsils to resolve long-standing land partition disputes and matrimonial grievances on the spot, sparing poor villagers expensive travel costs to district court complexes. Providing compassionate, accessible, and free legal aid upholds the constitutional guarantee of equal justice for all citizens across Rajasthan.`,
  84: `Additionally, convergence between the Forest Rights Act and rural housing schemes ensures that titled tribal families receive financial assistance to construct permanent pucca homes and install solar home-lighting systems. Providing secure land tenure empowers tribal communities, preserves indigenous ecological knowledge, and fosters inclusive economic growth across the forested districts of southern Rajasthan.`,
  85: `Moreover, continuous cyber security drills and threat simulation exercises conducted by state information security teams prepare treasury officials to respond swiftly to potential digital security breaches. Strict adherence to encrypted access protocols and multi-factor authentication safeguards state financial networks, ensuring that public treasury funds remain completely secure against evolving cyber threats.`,
  86: `Additionally, luxury royal trains and boutique heritage havelis introduce travelers to authentic regional cuisines, local textile traditions, and traditional folk dances, generating direct economic benefits for local artisans and desert performers. Sustaining heritage hospitality preserves Rajasthan architectural magnificence while establishing the state as an elite destination in global cultural tourism.`,
  87: `Furthermore, routine maintenance audits and computerized road condition surveys conducted by state highway engineers ensure that black-topped road surfaces remain safe and durable across all seasons. All-weather road networks stimulate local trade, enhance agrarian incomes, and connect remote rural families with essential healthcare and educational facilities throughout Rajasthan.`,
  88: `Moreover, the collective success of traditional Johad construction in reviving dead rivers demonstrates that decentralized water management is the most sustainable solution to arid water scarcity. Recharging subterranean aquifers restores lush agricultural fields and secures community drinking water supplies, providing an enduring model of ecological resilience for arid regions worldwide.`,
  89: `Additionally, establishing dedicated organic certification facilitation cells in district agriculture offices assists smallholder farmers in completing PGS-India documentation without procedural delays. Expanding chemical-free organic farming regenerates soil biology, protects underground aquifers, and delivers nutritious, safe food to families across Rajasthan.`,
  90: `Furthermore, community disaster response volunteers (Aapda Mitras) trained in flood rescue and first aid provide immediate emergency assistance before specialized battalions arrive at disaster sites. Equipping local communities with life-saving skills and early weather warnings saves human lives and enhances disaster resilience throughout Rajasthan.`,
  91: `Moreover, implementing centralized network performance monitoring software allows DoIT&C network engineers to detect bandwidth congestion and reroute data traffic dynamically during peak administrative hours. A reliable, high-speed public intranet infrastructure accelerates file movements and supports efficient, uninterrupted digital governance across Rajasthan.`,
  92: `Additionally, integrating the Pehchan portal with state demographic databases ensures that newly registered births automatically generate eligible welfare entitlements, such as immunization tracking and child healthcare notifications. Accurate civil registration guarantees legal identity for all citizens and provides vital statistical data for long-term state policy planning.`,
  94: `Furthermore, the state government is establishing specialized mining research wings in university geology departments to evaluate environmentally sustainable extraction methodologies for deep potash beds and rare earth complexes. Developing strategic mineral reserves will attract high-technology industrial investments, create skilled employment opportunities, and secure national self-reliance in critical green technologies.`,
  95: `Additionally, annual folk drama competitions organized in regional educational institutions inspire young drama students to study classical Rajasthani dramatic forms and learn regional theatrical dialects from veteran folk masters. Preserving traditional folk theatre keeps the historical memory, secular humor, and artistic soul of Rajasthan alive for future generations.`,
  96: `Moreover, automated drip-fertigation demonstrations conducted at district agricultural research stations show farmers how precision nutrient delivery increases fruit size and crop yields while cutting fertilizer expenses. Expanding micro-irrigation networks preserves finite groundwater resources and ensures sustainable agrarian prosperity across Rajasthan.`,
  97: `Additionally, the implementation of automated data encryption at rest and in transit across RajCloud virtual servers ensures that sensitive citizen records remain safeguarded against unauthorized digital intrusions. A modern, centralized state cloud infrastructure eliminates departmental silos, saves public expenditure, and powers agile e-governance applications across Rajasthan.`,
  98: `Furthermore, organizing regional craft authentication drives and issuing holographic GI labels for genuine hand-block printed textiles prevents market counterfeiting and reassures international buyers of product authenticity. Protecting Geographical Indications preserves priceless artistic legacies and guarantees fair economic returns for skilled artisan communities across Rajasthan.`,
  99: `Moreover, computerized reservation roster audits conducted by the Department of Personnel ensure that statutory employment quotas are implemented with mathematical accuracy and complete transparency across all recruitment cycles. Diligent establishment administration guarantees social justice, honors dedicated defense veterans, and builds an inclusive public service in Rajasthan.`,
  100: `Furthermore, regular district-level review meetings chaired by the Chief Secretary track real-time performance metrics on the Rajasthan SDG Dashboard, ensuring that government departments achieve their annual sustainability milestones. Committed civil servants and ministerial personnel serve as the vital driving force translating the vision of a prosperous, equitable, and sustainable Rajasthan into daily administrative reality.`
};

let code = fs.readFileSync(path.join(__dirname, 'generate_batch5.cjs'), 'utf8');

for (const [idStr, para] of Object.entries(extraBatch5)) {
  const id = parseInt(idStr);
  const regex = new RegExp(`(addLesson\\(${id},[\\s\\S]*?\\[[\\s\\S]*?)(\\n\\]\\);)`);
  const match = code.match(regex);
  if (match) {
    const replacement = `${match[1]},\n  \`${para.replace(/`/g, '\\`')}\`${match[2]}`;
    code = code.replace(regex, replacement);
    console.log(`Patched extra into Batch 5 Lesson ${id}`);
  } else {
    console.error(`Could not match Lesson ${id}`);
  }
}

fs.writeFileSync(path.join(__dirname, 'generate_batch5.cjs'), code, 'utf8');
console.log('Successfully patched Batch 5!');
